/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package wordpress.rs

import uniffi.wordpress_api.addCustom

class Library {
    fun addCustomFromRust(a: Int, b: Int): Int {
        return addCustom(a, b)
    }
}
