/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package wordpress.rs

import org.junit.Before
import org.junit.Test

class LibraryTest {
    @Before
    fun setup() {
    }
}
