[workspace]
members = [
  "wp_api",
  "wp_cli",
  "wp_derive",
  "wp_networking",
  "wp_uniffi_bindgen",
]
resolver = "2"

[workspace.dependencies]
uniffi = "0.27.0"
thiserror = "1.0"
# We need to match the version used in `reqwest`: https://github.com/seanmonstar/reqwest/blob/master/Cargo.toml#L84
# So that we can implement our own traits and it'll work with both reqwest types as well as http types
#
# For example, reqwest re-exports `http::StatusCode` as `reqwest::StatusCode` and as long as 
# we use the same version, we'll be able to implement our trait for `http::StatusCode` and it'll
# work for `reqwest::StatusCode` as well.
# https://github.com/seanmonstar/reqwest/blob/master/src/lib.rs#L252
#
# Note that there is a WIP PR that'll update the version used in `reqwest` to `1.0.0`:
# https://github.com/seanmonstar/reqwest/pull/2059
http = "0.2"
