[workspace]
members = [
  "wp_api",
  "wp_derive",
  "wp_networking",
  "wp_uniffi_bindgen",
]
resolver = "2"

[workspace.dependencies]
base64 = "0.22"
http = "1.1"
thiserror = "1.0"
uniffi = "0.27.0"
