[package]
name = "wp_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = { version = "1.0.89", features = ["diff"] }

[dependencies]
syn = { version = "2.0.52", features = ["extra-traits"] }
quote = "1.0.35"
proc-macro2 = "1.0.78"
