[package]
name = "jetpack"
version = "0.1.0"
edition = "2024"

[features]
integration-tests = []

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "jetpack"

[dependencies]
paste = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = [ "derive", "rc" ] }
serde_json = { workspace = true }
thiserror = { workspace = true }
uniffi = { workspace = true }
url = { workspace = true }
wp_api = { path = "../wp_api" }
wp_com = { path = "../wp_com" }
wp_contextual = { path = "../wp_contextual" }
wp_derive = { path = "../wp_derive" }
wp_derive_request_builder = { path = "../wp_derive_request_builder", features = [ "generate_request_builder" ] }

[dev-dependencies]
rstest = { workspace = true }
