/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rs.wordpress.api.android

import kotlinx.coroutines.test.runTest
import org.junit.Assert
import org.junit.Test
import rs.wordpress.api.kotlin.WpNetworkHandler
import rs.wordpress.api.kotlin.WpRequestSuccess
import rs.wordpress.api.kotlin.WpUsersEndpoint
import uniffi.wp_api.WpApiHelper
import uniffi.wp_api.wpAuthenticationFromUsernameAndPassword

private const val FIRST_USER_EMAIL = "test@example.com"
private const val NUMBER_OF_USERS = 3

class UsersEndpointAndroidTest {
    private val siteUrl = BuildConfig.TEST_SITE_URL
    private val authentication = wpAuthenticationFromUsernameAndPassword(
        username = BuildConfig.TEST_ADMIN_USERNAME,
        password = BuildConfig.TEST_ADMIN_PASSWORD
    )
    private val users =
        WpUsersEndpoint(WpNetworkHandler(), apiHelper = WpApiHelper(siteUrl, authentication))

    @Test
    fun testUserListRequest() = runTest {
        val result = users.list.withEditContext(params = null)
        assert(result is WpRequestSuccess)
        val userList = (result as WpRequestSuccess).data
        Assert.assertEquals(NUMBER_OF_USERS, userList.count())
        Assert.assertEquals(FIRST_USER_EMAIL, userList.first().email)
    }
}
