[package]
name = "wp_parsing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_parsing"

[dependencies]
uniffi = { workspace = true }
wp_api = { path = "../wp_api" }

[build-dependencies]
uniffi = { workspace = true, features = [ "build", "cli" ]  }
