[package]
name = "wp_parsing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]
name = "wp_parsing"

[dependencies]
uniffi = { version = "0.25.0" }

[build-dependencies]
uniffi = { version = "0.25.0", features = [ "build", "cli" ] }
