[package]
name = "wp_mobile"
version = "0.1.0"
edition = "2024"

[features]
reqwest-request-executor = ["wp_api/reqwest-request-executor"]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_mobile"

[dependencies]
uniffi = { workspace = true }
wp_api = { path = "../wp_api" }

[build-dependencies]
uniffi = { workspace = true , features = [ "build", "cli" ] }
