[package]
name = "wp_mobile"
version = "0.1.0"
edition = "2024"

[features]
reqwest-request-executor = ["wp_api/reqwest-request-executor"]
export-uncancellable-endpoints = ["wp_api/export-uncancellable-endpoints"]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_mobile"

[dependencies]
log = { workspace = true }
paste = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
uniffi = { workspace = true }
url = { workspace = true }
wp_api = { path = "../wp_api" }
wp_mobile_cache = { path = "../wp_mobile_cache" }

[dev-dependencies]
async-trait = { workspace = true }
rstest = { workspace = true }
rusqlite = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
wp_mobile_cache = { path = "../wp_mobile_cache", features = ["test-helpers"] }

[build-dependencies]
uniffi = { workspace = true , features = [ "build", "cli" ] }
