steps:
  - label: ":wordpress: :rust: WordPress.org API"
    command: |
      echo "--- :rust: Testing"
      make test-rust-integration-wordpress-org-api
    notify:
      - slack:
          channels:
            - "#wordpress-rs"
          message: "Nightly build failed."
        if: build.state == "failed"
    env:
      TEST_ALL_PLUGINS: true

  - label: ":globe_with_meridians: :arrow_up: :arrow_down: Sync localization"
    command: .buildkite/commands/sync-localization.sh
    notify:
      - slack:
          channels:
            - "#wordpress-rs"
          message: "Localization sync failed."
        if: build.state == "failed"
    env:
      IMAGE_ID: $IMAGE_ID
    agents:
      queue: mac
