# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#3.4.1
  # Common environment values to use with the `env` key.

steps:
  #
  # Rust Group
  - group: ":rust: Core Library"
    key: "rust"
    steps:
      - label: ":rust: Build and Test"
        command: |
          echo "--- :rust: Building + Testing"
          make test-rust-lib
          make test-rust-doc
      - label: ":rust: Test `#[derive(WpDerivedRequest)]` Parser"
        command: |
          # Once we have integration tests running in CI, we can remove this separate step
          echo "--- :rust: Testing `#[derive(WpDerivedRequest)]` Parser"
          make test-rust-wp-derived-request-parser
      - label: ":rust: Lint"
        command: |
          echo "--- :rust: Running Clippy"
          make lint-rust

          echo "--- :rust: Ensuring Code Conforms to rustfmt"
          make fmt-check-rust
      - label: ":rust: Build Docs"
        command: |
          echo "--- :rust: Building Documentation"
          make docs-archive
        artifact_paths:
          - docs.tar.gz

  #
  # Swift Group
  - group: ":swift: Swift Wrapper"
    key: "swift"
    steps:
      - label: ":swift: :darwin: Build xcframework"
        key: "xcframework"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y

          source "/Users/builder/.cargo/env"

          echo "--- :package: Installing Rust Toolchains"
          make setup-rust

          echo "--- :swift: Building xcframework"
          make xcframework
          zip -r target/libwordpressFFI.xcframework.zip target/libwordpressFFI.xcframework
        artifact_paths:
          - target/libwordpressFFI.xcframework.zip
          - native/swift/Sources/wordpress-api-wrapper/wp_api.swift
        env:
          IMAGE_ID: xcode-15.3
        agents:
          queue: mac
      - label: ":swift: :darwin: Build + Test on Simulators"
        command: .buildkite/swift-test.sh run_tests
        env:
          IMAGE_ID: xcode-15.3
        depends_on: xcframework
        plugins: *common_plugins
        agents:
          queue: mac
      - label: ":swift: :darwin: Build for Real Devices"
        command: .buildkite/swift-test.sh build_for_real_device
        env:
          IMAGE_ID: xcode-15.3
        depends_on: xcframework
        plugins: *common_plugins
        agents:
          queue: mac
      - label: ":swift: :cocoapods: Validate CocoaPods Support"
        command: .buildkite/validate-cocoapods.sh
        env:
          IMAGE_ID: xcode-15.3
        depends_on: xcframework
        plugins: *common_plugins
        agents:
          queue: mac
      - label: ":swift: :linux: Build and Test"
        command: |
          echo "--- :swift: Building + Testing"
          make test-swift-linux
      - label: ":swift: Lint"
        command: |
          .buildkite/download-xcframework.sh
          echo "--- :swift: Swiftlint"
          make lint-swift
        depends_on: xcframework
        env:
          IMAGE_ID: xcode-15.3
        agents:
          queue: mac
      - label: ":swift: Example Apps"
        command: |
          .buildkite/download-xcframework.sh

          echo "--- :computer: Building for macOS"
          make swift-example-app-mac

          echo "--- :iphone: Building for iOS"
          make swift-example-app-ios
        depends_on: xcframework
        env:
          IMAGE_ID: xcode-15.3
        agents:
          queue: mac
  #
  # Kotlin Group
  - group: ":kotlin: Kotlin Wrapper"
    key: "kotlin"
    steps:
      - label: ":kotlin: Detekt"
        key: "kotlin-detekt"
        plugins: *common_plugins
        artifact_paths:
          - "**/build/reports/detekt/detekt.html"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y

          source "$$HOME/.cargo/env"

          echo "--- :package: Installing Rust Toolchains"
          make setup-rust
          make setup-rust-android-targets

          echo "--- 🧹 Linting"

          # This is a temporary step until we implement a more graceful way to handle missing credentials
          printf "site_url\nadmin_username\nadmin_password\nadmin_password_uuid\nsubscriber_username\nsubscriber_password\nsubscriber_password_uuid\n" > test_credentials

          cd ./native/kotlin
          ./gradlew detektMain detektTest
        agents:
          queue: android
      - label: ":kotlin: Publish `rs.wordpress.api:kotlin`"
        key: "publish-wp-api-kotlin"
        plugins: *common_plugins
        depends_on:
          - "kotlin-detekt"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y

          source "$$HOME/.cargo/env"

          echo "--- :package: Installing Rust Toolchains"
          make setup-rust

          echo "--- :kotlin: Publishing `rs.wordpress.api:kotlin`"
          .buildkite/publish-wp-api-kotlin.sh
        agents:
          queue: android
      - label: ":kotlin: Publish `rs.wordpress.api:android`"
        key: "publish-wp-api-android"
        plugins: *common_plugins
        depends_on:
          - "publish-wp-api-kotlin"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y

          source "$$HOME/.cargo/env"

          echo "--- :package: Installing Rust Toolchains"
          make setup-rust
          make setup-rust-android-targets

          echo "--- :kotlin: Publishing `rs.wordpress.api:android`"
          .buildkite/publish-wp-api-android.sh
        agents:
          queue: android
  #
  # Docker Group
  - group: ":wordpress: End-to-end Tests"
    key: "e2e"
    steps:
      - label: ":wordpress: WordPress {{matrix}}"
        command: |
          echo "--- :docker: Setting up Test Server"
          make test-server

          echo "--- 🧪 Running Tests"
          make test-rust-integration
        env:
          WORDPRESS_VERSION: "{{matrix}}"
        matrix:
          - '5.6' # First version to introduce appliation passwords
          - '5.7'
          - '5.8'
          - '5.9'
          - '6.0'
          - '6.1'
          - '6.2'
          - '6.3'
          - '6.4'
          - '6.5'
          - '6.6'

  - label: ":rocket: Publish release $NEW_VERSION"
    command: .buildkite/release.sh $NEW_VERSION
    depends_on: swift
    plugins: *common_plugins
    env:
      IMAGE_ID: xcode-15.4
    agents:
      queue: mac
    if: build.env("NEW_VERSION") != null
