# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#2.17.0
  # Common environment values to use with the `env` key.

steps:
  #
  # Rust Group
  - group: ":rust: Core Library"
    key: "rust"
    steps:
      - label: ":rust: Build and Test"
        command: |
          echo "--- :rust: Building + Testing"
          make test-rust-lib
          make test-rust-doc
      - label: ":rust: Lint"
        command: |
          echo "--- :rust: Running Clippy"
          make lint-rust

          echo "--- :rust: Ensuring Code Conforms to rustfmt"
          make fmt-check-rust
      - label: ":rust: Build Docs"
        command: |
          echo "--- :rust: Building Documentation"
          make docs-archive
        artifact_paths:
          - docs.tar.gz

  #
  # Swift Group
  - group: ":swift: Swift Wrapper"
    key: "swift"
    steps:
      - label: ":swift: :darwin: Build xcframework"
        key: "xcframework"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y

          source "/Users/builder/.cargo/env"

          echo "--- :package: Installing Rust Toolchains"
          make setup-rust

          echo "--- :swift: Building xcframework"
          make xcframework
          zip -r target/libwordpressFFI.xcframework.zip target/libwordpressFFI.xcframework
        artifact_paths:
          - target/libwordpressFFI.xcframework.zip
          - native/swift/Sources/wordpress-api-wrapper/wp_api.swift
        env:
          IMAGE_ID: xcode-15.3
        agents:
          queue: mac
      - label: ":swift: :darwin: Build + Test on Simulators"
        command: .buildkite/swift-test.sh run_tests
        env:
          IMAGE_ID: xcode-15.3
        depends_on: xcframework
        plugins: *common_plugins
        agents:
          queue: mac
      - label: ":swift: :darwin: Build for Real Devices"
        command: .buildkite/swift-test.sh build_for_real_device
        env:
          IMAGE_ID: xcode-15.3
        depends_on: xcframework
        plugins: *common_plugins
        agents:
          queue: mac
      - label: ":swift: :linux: Build and Test"
        command: |
          echo "--- :swift: Building + Testing"
          make test-swift-linux
      - label: ":swift: Lint"
        command: |
          echo "--- :swift: Swiftlint"
          make lint-swift
  #
  # Kotlin Group
  - group: ":kotlin: Kotlin Wrapper"
    key: "kotlin"
    steps:
      - label: ":kotlin: Publish `rs.wordpress.api:kotlin`"
        key: "publish-wp-api-kotlin"
        plugins: *common_plugins
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y

          source "$$HOME/.cargo/env"

          echo "--- :package: Installing Rust Toolchains"
          make setup-rust

          echo "--- :kotlin: Publishing `rs.wordpress.api:kotlin`"
          .buildkite/publish-wp-api-kotlin.sh
        agents:
          queue: android
      - label: ":kotlin: Publish `rs.wordpress.api:android`"
        key: "publish-wp-api-android"
        plugins: *common_plugins
        depends_on:
          - "publish-wp-api-kotlin"
        command: |
          echo "--- :rust: Installing Rust"
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -v -y

          source "$$HOME/.cargo/env"

          echo "--- :package: Installing Rust Toolchains"
          make setup-rust
          make setup-rust-android-targets

          echo "--- :kotlin: Publishing `rs.wordpress.api:android`"
          .buildkite/publish-wp-api-android.sh
        agents:
          queue: android
  #
  # Docker Group
  - group: ":wordpress: End-to-end Tests"
    key: "e2e"
    steps:
      - label: ":wordpress: WordPress {{matrix}}"
        command: |
          echo "--- :docker: Setting up Test Server"
          make test-server

          echo "--- 🧪 Running Tests"
          curl -u $(cat test_credentials | sed -n '2 p'):$(cat test_credentials | sed -n '3 p') 'http://localhost/wp-json/wp/v2/posts?context=edit' --fail-with-body | jq
        env:
          WORDPRESS_VERSION: "{{matrix}}"
        matrix:
          - '6.4'
          - '6.3'
          - '6.2'
          - '6.1'
          - '6.0'
          - '5.9'
          - '5.8'
          - '5.7'
          - '5.6' # First version to introduce appliation passwords
