#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

XCODE_VERSION="16.0-v7"
CI_TOOLKIT_PLUGIN_VERSION="3.7.1"
TEST_COLLECTOR_VERSION="v1.10.2"

export IMAGE_ID="xcode-$XCODE_VERSION"
export CI_TOOLKIT="automattic/a8c-ci-toolkit#$CI_TOOLKIT_PLUGIN_VERSION"
export TEST_COLLECTOR="test-collector#$TEST_COLLECTOR_VERSION"
