// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(libwordpressFFI)
import libwordpressFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_jetpack_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_jetpack_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureJetpackInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ConnectionRequestBuilderProtocol: AnyObject, Sendable {
    
    func connection()  -> WpNetworkRequest
    
    func connectionCheck()  -> WpNetworkRequest
    
    func connectionData()  -> WpNetworkRequest
    
    func register(params: JetpackConnectionParams)  -> WpNetworkRequest
    
    func remoteProvision(params: JetpackRemoteProvisionParams)  -> WpNetworkRequest
    
}
open class ConnectionRequestBuilder: ConnectionRequestBuilderProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_jetpack_fn_clone_connectionrequestbuilder(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_jetpack_fn_free_connectionrequestbuilder(pointer, $0) }
    }

    

    
open func connection() -> WpNetworkRequest  {
    return try!  FfiConverterTypeWpNetworkRequest_lift(try! rustCall() {
    uniffi_jetpack_fn_method_connectionrequestbuilder_connection(self.uniffiClonePointer(),$0
    )
})
}
    
open func connectionCheck() -> WpNetworkRequest  {
    return try!  FfiConverterTypeWpNetworkRequest_lift(try! rustCall() {
    uniffi_jetpack_fn_method_connectionrequestbuilder_connection_check(self.uniffiClonePointer(),$0
    )
})
}
    
open func connectionData() -> WpNetworkRequest  {
    return try!  FfiConverterTypeWpNetworkRequest_lift(try! rustCall() {
    uniffi_jetpack_fn_method_connectionrequestbuilder_connection_data(self.uniffiClonePointer(),$0
    )
})
}
    
open func register(params: JetpackConnectionParams) -> WpNetworkRequest  {
    return try!  FfiConverterTypeWpNetworkRequest_lift(try! rustCall() {
    uniffi_jetpack_fn_method_connectionrequestbuilder_register(self.uniffiClonePointer(),
        FfiConverterTypeJetpackConnectionParams_lower(params),$0
    )
})
}
    
open func remoteProvision(params: JetpackRemoteProvisionParams) -> WpNetworkRequest  {
    return try!  FfiConverterTypeWpNetworkRequest_lift(try! rustCall() {
    uniffi_jetpack_fn_method_connectionrequestbuilder_remote_provision(self.uniffiClonePointer(),
        FfiConverterTypeJetpackRemoteProvisionParams_lower(params),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionRequestBuilder: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ConnectionRequestBuilder

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ConnectionRequestBuilder {
        return ConnectionRequestBuilder(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ConnectionRequestBuilder) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionRequestBuilder {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ConnectionRequestBuilder, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestBuilder_lift(_ pointer: UnsafeMutableRawPointer) throws -> ConnectionRequestBuilder {
    return try FfiConverterTypeConnectionRequestBuilder.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestBuilder_lower(_ value: ConnectionRequestBuilder) -> UnsafeMutableRawPointer {
    return FfiConverterTypeConnectionRequestBuilder.lower(value)
}






public protocol ConnectionRequestExecutorProtocol: AnyObject, Sendable {
    
    func connection() async throws  -> ConnectionRequestConnectionResponse
    
    func connectionCheck() async throws  -> ConnectionRequestConnectionCheckResponse
    
    func connectionData() async throws  -> ConnectionRequestConnectionDataResponse
    
    func fetchAuthenticationState() async throws  -> AuthenticationState
    
    func register(params: JetpackConnectionParams) async throws  -> ConnectionRequestRegisterResponse
    
    func remoteProvision(params: JetpackRemoteProvisionParams) async throws  -> ConnectionRequestRemoteProvisionResponse
    
}
open class ConnectionRequestExecutor: ConnectionRequestExecutorProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_jetpack_fn_clone_connectionrequestexecutor(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_jetpack_fn_free_connectionrequestexecutor(pointer, $0) }
    }

    

    
open func connection()async throws  -> ConnectionRequestConnectionResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_connectionrequestexecutor_connection(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_rust_buffer,
            completeFunc: ffi_jetpack_rust_future_complete_rust_buffer,
            freeFunc: ffi_jetpack_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeConnectionRequestConnectionResponse_lift,
            errorHandler: FfiConverterTypeWpApiError_lift
        )
}
    
open func connectionCheck()async throws  -> ConnectionRequestConnectionCheckResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_connectionrequestexecutor_connection_check(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_rust_buffer,
            completeFunc: ffi_jetpack_rust_future_complete_rust_buffer,
            freeFunc: ffi_jetpack_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeConnectionRequestConnectionCheckResponse_lift,
            errorHandler: FfiConverterTypeWpApiError_lift
        )
}
    
open func connectionData()async throws  -> ConnectionRequestConnectionDataResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_connectionrequestexecutor_connection_data(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_rust_buffer,
            completeFunc: ffi_jetpack_rust_future_complete_rust_buffer,
            freeFunc: ffi_jetpack_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeConnectionRequestConnectionDataResponse_lift,
            errorHandler: FfiConverterTypeWpApiError_lift
        )
}
    
open func fetchAuthenticationState()async throws  -> AuthenticationState  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_connectionrequestexecutor_fetch_authentication_state(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_rust_buffer,
            completeFunc: ffi_jetpack_rust_future_complete_rust_buffer,
            freeFunc: ffi_jetpack_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeAuthenticationState_lift,
            errorHandler: FfiConverterTypeWpApiError_lift
        )
}
    
open func register(params: JetpackConnectionParams)async throws  -> ConnectionRequestRegisterResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_connectionrequestexecutor_register(
                    self.uniffiClonePointer(),
                    FfiConverterTypeJetpackConnectionParams_lower(params)
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_rust_buffer,
            completeFunc: ffi_jetpack_rust_future_complete_rust_buffer,
            freeFunc: ffi_jetpack_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeConnectionRequestRegisterResponse_lift,
            errorHandler: FfiConverterTypeWpApiError_lift
        )
}
    
open func remoteProvision(params: JetpackRemoteProvisionParams)async throws  -> ConnectionRequestRemoteProvisionResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_connectionrequestexecutor_remote_provision(
                    self.uniffiClonePointer(),
                    FfiConverterTypeJetpackRemoteProvisionParams_lower(params)
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_rust_buffer,
            completeFunc: ffi_jetpack_rust_future_complete_rust_buffer,
            freeFunc: ffi_jetpack_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeConnectionRequestRemoteProvisionResponse_lift,
            errorHandler: FfiConverterTypeWpApiError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionRequestExecutor: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ConnectionRequestExecutor

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ConnectionRequestExecutor {
        return ConnectionRequestExecutor(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ConnectionRequestExecutor) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionRequestExecutor {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ConnectionRequestExecutor, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestExecutor_lift(_ pointer: UnsafeMutableRawPointer) throws -> ConnectionRequestExecutor {
    return try FfiConverterTypeConnectionRequestExecutor.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestExecutor_lower(_ value: ConnectionRequestExecutor) -> UnsafeMutableRawPointer {
    return FfiConverterTypeConnectionRequestExecutor.lower(value)
}






/**
 * Connect a WordPress site to Jetpack.
 *
 * Please note, the endpoints used are available on Jetpack 14.2 and above.
 */
public protocol JetpackConnectionClientProtocol: AnyObject, Sendable {
    
    func connectSite(from: String) async throws  -> WpComSiteId
    
    func connectUser(wpComAuthentication: WpAuthentication, from: String) async throws  -> WpComSiteId
    
    func status() async throws  -> JetpackConnectionStatus
    
}
/**
 * Connect a WordPress site to Jetpack.
 *
 * Please note, the endpoints used are available on Jetpack 14.2 and above.
 */
open class JetpackConnectionClient: JetpackConnectionClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_jetpack_fn_clone_jetpackconnectionclient(self.pointer, $0) }
    }
public convenience init(apiRootUrl: ParsedUrl, delegate: WpApiClientDelegate) {
    let pointer =
        try! rustCall() {
    uniffi_jetpack_fn_constructor_jetpackconnectionclient_new(
        FfiConverterTypeParsedUrl_lower(apiRootUrl),
        FfiConverterTypeWpApiClientDelegate_lower(delegate),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_jetpack_fn_free_jetpackconnectionclient(pointer, $0) }
    }

    

    
open func connectSite(from: String)async throws  -> WpComSiteId  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_jetpackconnectionclient_connect_site(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(from)
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_u64,
            completeFunc: ffi_jetpack_rust_future_complete_u64,
            freeFunc: ffi_jetpack_rust_future_free_u64,
            liftFunc: FfiConverterTypeWpComSiteId_lift,
            errorHandler: FfiConverterTypeJetpackConnectionClientError_lift
        )
}
    
open func connectUser(wpComAuthentication: WpAuthentication, from: String)async throws  -> WpComSiteId  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_jetpackconnectionclient_connect_user(
                    self.uniffiClonePointer(),
                    FfiConverterTypeWpAuthentication_lower(wpComAuthentication),FfiConverterString.lower(from)
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_u64,
            completeFunc: ffi_jetpack_rust_future_complete_u64,
            freeFunc: ffi_jetpack_rust_future_free_u64,
            liftFunc: FfiConverterTypeWpComSiteId_lift,
            errorHandler: FfiConverterTypeJetpackConnectionClientError_lift
        )
}
    
open func status()async throws  -> JetpackConnectionStatus  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_jetpack_fn_method_jetpackconnectionclient_status(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_jetpack_rust_future_poll_rust_buffer,
            completeFunc: ffi_jetpack_rust_future_complete_rust_buffer,
            freeFunc: ffi_jetpack_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeJetpackConnectionStatus_lift,
            errorHandler: FfiConverterTypeJetpackConnectionClientError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = JetpackConnectionClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> JetpackConnectionClient {
        return JetpackConnectionClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: JetpackConnectionClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: JetpackConnectionClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> JetpackConnectionClient {
    return try FfiConverterTypeJetpackConnectionClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionClient_lower(_ value: JetpackConnectionClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeJetpackConnectionClient.lower(value)
}






public protocol UniffiJetpackApiClientProtocol: AnyObject, Sendable {
    
    func connection()  -> ConnectionRequestExecutor
    
}
open class UniffiJetpackApiClient: UniffiJetpackApiClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_jetpack_fn_clone_uniffijetpackapiclient(self.pointer, $0) }
    }
public convenience init(siteUrl: ParsedUrl, delegate: WpApiClientDelegate) {
    let pointer =
        try! rustCall() {
    uniffi_jetpack_fn_constructor_uniffijetpackapiclient_new(
        FfiConverterTypeParsedUrl_lower(siteUrl),
        FfiConverterTypeWpApiClientDelegate_lower(delegate),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_jetpack_fn_free_uniffijetpackapiclient(pointer, $0) }
    }

    

    
open func connection() -> ConnectionRequestExecutor  {
    return try!  FfiConverterTypeConnectionRequestExecutor_lift(try! rustCall() {
    uniffi_jetpack_fn_method_uniffijetpackapiclient_connection(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUniffiJetpackApiClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = UniffiJetpackApiClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiJetpackApiClient {
        return UniffiJetpackApiClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: UniffiJetpackApiClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UniffiJetpackApiClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: UniffiJetpackApiClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiJetpackApiClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiJetpackApiClient {
    return try FfiConverterTypeUniffiJetpackApiClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiJetpackApiClient_lower(_ value: UniffiJetpackApiClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeUniffiJetpackApiClient.lower(value)
}






public protocol UniffiJetpackApiRequestBuilderProtocol: AnyObject, Sendable {
    
    func connection()  -> ConnectionRequestBuilder
    
}
open class UniffiJetpackApiRequestBuilder: UniffiJetpackApiRequestBuilderProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_jetpack_fn_clone_uniffijetpackapirequestbuilder(self.pointer, $0) }
    }
public convenience init(apiRootUrl: ParsedUrl, authProvider: WpAuthenticationProvider) {
    let pointer =
        try! rustCall() {
    uniffi_jetpack_fn_constructor_uniffijetpackapirequestbuilder_new(
        FfiConverterTypeParsedUrl_lower(apiRootUrl),
        FfiConverterTypeWpAuthenticationProvider_lower(authProvider),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_jetpack_fn_free_uniffijetpackapirequestbuilder(pointer, $0) }
    }

    

    
open func connection() -> ConnectionRequestBuilder  {
    return try!  FfiConverterTypeConnectionRequestBuilder_lift(try! rustCall() {
    uniffi_jetpack_fn_method_uniffijetpackapirequestbuilder_connection(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUniffiJetpackApiRequestBuilder: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = UniffiJetpackApiRequestBuilder

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiJetpackApiRequestBuilder {
        return UniffiJetpackApiRequestBuilder(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: UniffiJetpackApiRequestBuilder) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UniffiJetpackApiRequestBuilder {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: UniffiJetpackApiRequestBuilder, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiJetpackApiRequestBuilder_lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiJetpackApiRequestBuilder {
    return try FfiConverterTypeUniffiJetpackApiRequestBuilder.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiJetpackApiRequestBuilder_lower(_ value: UniffiJetpackApiRequestBuilder) -> UnsafeMutableRawPointer {
    return FfiConverterTypeUniffiJetpackApiRequestBuilder.lower(value)
}




public struct ConnectionRequestConnectionCheckResponse {
    public let data: JetpackConnectionCheck
    public let headerMap: WpNetworkHeaderMap

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(data: JetpackConnectionCheck, headerMap: WpNetworkHeaderMap) {
        self.data = data
        self.headerMap = headerMap
    }
}

#if compiler(>=6)
extension ConnectionRequestConnectionCheckResponse: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionRequestConnectionCheckResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionRequestConnectionCheckResponse {
        return
            try ConnectionRequestConnectionCheckResponse(
                data: FfiConverterTypeJetpackConnectionCheck.read(from: &buf), 
                headerMap: FfiConverterTypeWpNetworkHeaderMap.read(from: &buf)
        )
    }

    public static func write(_ value: ConnectionRequestConnectionCheckResponse, into buf: inout [UInt8]) {
        FfiConverterTypeJetpackConnectionCheck.write(value.data, into: &buf)
        FfiConverterTypeWpNetworkHeaderMap.write(value.headerMap, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestConnectionCheckResponse_lift(_ buf: RustBuffer) throws -> ConnectionRequestConnectionCheckResponse {
    return try FfiConverterTypeConnectionRequestConnectionCheckResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestConnectionCheckResponse_lower(_ value: ConnectionRequestConnectionCheckResponse) -> RustBuffer {
    return FfiConverterTypeConnectionRequestConnectionCheckResponse.lower(value)
}


public struct ConnectionRequestConnectionDataResponse {
    public let data: JetpackConnectionData
    public let headerMap: WpNetworkHeaderMap

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(data: JetpackConnectionData, headerMap: WpNetworkHeaderMap) {
        self.data = data
        self.headerMap = headerMap
    }
}

#if compiler(>=6)
extension ConnectionRequestConnectionDataResponse: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionRequestConnectionDataResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionRequestConnectionDataResponse {
        return
            try ConnectionRequestConnectionDataResponse(
                data: FfiConverterTypeJetpackConnectionData.read(from: &buf), 
                headerMap: FfiConverterTypeWpNetworkHeaderMap.read(from: &buf)
        )
    }

    public static func write(_ value: ConnectionRequestConnectionDataResponse, into buf: inout [UInt8]) {
        FfiConverterTypeJetpackConnectionData.write(value.data, into: &buf)
        FfiConverterTypeWpNetworkHeaderMap.write(value.headerMap, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestConnectionDataResponse_lift(_ buf: RustBuffer) throws -> ConnectionRequestConnectionDataResponse {
    return try FfiConverterTypeConnectionRequestConnectionDataResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestConnectionDataResponse_lower(_ value: ConnectionRequestConnectionDataResponse) -> RustBuffer {
    return FfiConverterTypeConnectionRequestConnectionDataResponse.lower(value)
}


public struct ConnectionRequestConnectionResponse {
    public let data: JetpackConnection
    public let headerMap: WpNetworkHeaderMap

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(data: JetpackConnection, headerMap: WpNetworkHeaderMap) {
        self.data = data
        self.headerMap = headerMap
    }
}

#if compiler(>=6)
extension ConnectionRequestConnectionResponse: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionRequestConnectionResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionRequestConnectionResponse {
        return
            try ConnectionRequestConnectionResponse(
                data: FfiConverterTypeJetpackConnection.read(from: &buf), 
                headerMap: FfiConverterTypeWpNetworkHeaderMap.read(from: &buf)
        )
    }

    public static func write(_ value: ConnectionRequestConnectionResponse, into buf: inout [UInt8]) {
        FfiConverterTypeJetpackConnection.write(value.data, into: &buf)
        FfiConverterTypeWpNetworkHeaderMap.write(value.headerMap, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestConnectionResponse_lift(_ buf: RustBuffer) throws -> ConnectionRequestConnectionResponse {
    return try FfiConverterTypeConnectionRequestConnectionResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestConnectionResponse_lower(_ value: ConnectionRequestConnectionResponse) -> RustBuffer {
    return FfiConverterTypeConnectionRequestConnectionResponse.lower(value)
}


public struct ConnectionRequestRegisterResponse {
    public let data: JetpackConnectionRegisterResult
    public let headerMap: WpNetworkHeaderMap

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(data: JetpackConnectionRegisterResult, headerMap: WpNetworkHeaderMap) {
        self.data = data
        self.headerMap = headerMap
    }
}

#if compiler(>=6)
extension ConnectionRequestRegisterResponse: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionRequestRegisterResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionRequestRegisterResponse {
        return
            try ConnectionRequestRegisterResponse(
                data: FfiConverterTypeJetpackConnectionRegisterResult.read(from: &buf), 
                headerMap: FfiConverterTypeWpNetworkHeaderMap.read(from: &buf)
        )
    }

    public static func write(_ value: ConnectionRequestRegisterResponse, into buf: inout [UInt8]) {
        FfiConverterTypeJetpackConnectionRegisterResult.write(value.data, into: &buf)
        FfiConverterTypeWpNetworkHeaderMap.write(value.headerMap, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestRegisterResponse_lift(_ buf: RustBuffer) throws -> ConnectionRequestRegisterResponse {
    return try FfiConverterTypeConnectionRequestRegisterResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestRegisterResponse_lower(_ value: ConnectionRequestRegisterResponse) -> RustBuffer {
    return FfiConverterTypeConnectionRequestRegisterResponse.lower(value)
}


public struct ConnectionRequestRemoteProvisionResponse {
    public let data: JetpackRemoteProvisionResult
    public let headerMap: WpNetworkHeaderMap

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(data: JetpackRemoteProvisionResult, headerMap: WpNetworkHeaderMap) {
        self.data = data
        self.headerMap = headerMap
    }
}

#if compiler(>=6)
extension ConnectionRequestRemoteProvisionResponse: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionRequestRemoteProvisionResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionRequestRemoteProvisionResponse {
        return
            try ConnectionRequestRemoteProvisionResponse(
                data: FfiConverterTypeJetpackRemoteProvisionResult.read(from: &buf), 
                headerMap: FfiConverterTypeWpNetworkHeaderMap.read(from: &buf)
        )
    }

    public static func write(_ value: ConnectionRequestRemoteProvisionResponse, into buf: inout [UInt8]) {
        FfiConverterTypeJetpackRemoteProvisionResult.write(value.data, into: &buf)
        FfiConverterTypeWpNetworkHeaderMap.write(value.headerMap, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestRemoteProvisionResponse_lift(_ buf: RustBuffer) throws -> ConnectionRequestRemoteProvisionResponse {
    return try FfiConverterTypeConnectionRequestRemoteProvisionResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionRequestRemoteProvisionResponse_lower(_ value: ConnectionRequestRemoteProvisionResponse) -> RustBuffer {
    return FfiConverterTypeConnectionRequestRemoteProvisionResponse.lower(value)
}


public struct JetpackConnection {
    public let isActive: Bool
    public let isUserConnected: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(isActive: Bool, isUserConnected: Bool) {
        self.isActive = isActive
        self.isUserConnected = isUserConnected
    }
}

#if compiler(>=6)
extension JetpackConnection: Sendable {}
#endif


extension JetpackConnection: Equatable, Hashable {
    public static func ==(lhs: JetpackConnection, rhs: JetpackConnection) -> Bool {
        if lhs.isActive != rhs.isActive {
            return false
        }
        if lhs.isUserConnected != rhs.isUserConnected {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(isActive)
        hasher.combine(isUserConnected)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnection {
        return
            try JetpackConnection(
                isActive: FfiConverterBool.read(from: &buf), 
                isUserConnected: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackConnection, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.isActive, into: &buf)
        FfiConverterBool.write(value.isUserConnected, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnection_lift(_ buf: RustBuffer) throws -> JetpackConnection {
    return try FfiConverterTypeJetpackConnection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnection_lower(_ value: JetpackConnection) -> RustBuffer {
    return FfiConverterTypeJetpackConnection.lower(value)
}


public struct JetpackConnectionCheck {
    public let status: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(status: String) {
        self.status = status
    }
}

#if compiler(>=6)
extension JetpackConnectionCheck: Sendable {}
#endif


extension JetpackConnectionCheck: Equatable, Hashable {
    public static func ==(lhs: JetpackConnectionCheck, rhs: JetpackConnectionCheck) -> Bool {
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(status)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionCheck: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionCheck {
        return
            try JetpackConnectionCheck(
                status: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackConnectionCheck, into buf: inout [UInt8]) {
        FfiConverterString.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionCheck_lift(_ buf: RustBuffer) throws -> JetpackConnectionCheck {
    return try FfiConverterTypeJetpackConnectionCheck.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionCheck_lower(_ value: JetpackConnectionCheck) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionCheck.lower(value)
}


public struct JetpackConnectionData {
    public let currentUser: JetpackConnectionUser
    public let connectionOwner: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(currentUser: JetpackConnectionUser, connectionOwner: String?) {
        self.currentUser = currentUser
        self.connectionOwner = connectionOwner
    }
}

#if compiler(>=6)
extension JetpackConnectionData: Sendable {}
#endif


extension JetpackConnectionData: Equatable, Hashable {
    public static func ==(lhs: JetpackConnectionData, rhs: JetpackConnectionData) -> Bool {
        if lhs.currentUser != rhs.currentUser {
            return false
        }
        if lhs.connectionOwner != rhs.connectionOwner {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(currentUser)
        hasher.combine(connectionOwner)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionData {
        return
            try JetpackConnectionData(
                currentUser: FfiConverterTypeJetpackConnectionUser.read(from: &buf), 
                connectionOwner: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackConnectionData, into buf: inout [UInt8]) {
        FfiConverterTypeJetpackConnectionUser.write(value.currentUser, into: &buf)
        FfiConverterOptionString.write(value.connectionOwner, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionData_lift(_ buf: RustBuffer) throws -> JetpackConnectionData {
    return try FfiConverterTypeJetpackConnectionData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionData_lower(_ value: JetpackConnectionData) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionData.lower(value)
}


public struct JetpackConnectionParams {
    /**
     * origination of the request, e.g. "jetpack-app"
     */
    public let from: String
    /**
     * the plugin being connected, e.g. "jetpack"
     */
    public let pluginSlug: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * origination of the request, e.g. "jetpack-app"
         */from: String, 
        /**
         * the plugin being connected, e.g. "jetpack"
         */pluginSlug: String) {
        self.from = from
        self.pluginSlug = pluginSlug
    }
}

#if compiler(>=6)
extension JetpackConnectionParams: Sendable {}
#endif


extension JetpackConnectionParams: Equatable, Hashable {
    public static func ==(lhs: JetpackConnectionParams, rhs: JetpackConnectionParams) -> Bool {
        if lhs.from != rhs.from {
            return false
        }
        if lhs.pluginSlug != rhs.pluginSlug {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(from)
        hasher.combine(pluginSlug)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionParams {
        return
            try JetpackConnectionParams(
                from: FfiConverterString.read(from: &buf), 
                pluginSlug: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackConnectionParams, into buf: inout [UInt8]) {
        FfiConverterString.write(value.from, into: &buf)
        FfiConverterString.write(value.pluginSlug, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionParams_lift(_ buf: RustBuffer) throws -> JetpackConnectionParams {
    return try FfiConverterTypeJetpackConnectionParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionParams_lower(_ value: JetpackConnectionParams) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionParams.lower(value)
}


public struct JetpackConnectionRegisterResult {
    public let authorizeUrl: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(authorizeUrl: String) {
        self.authorizeUrl = authorizeUrl
    }
}

#if compiler(>=6)
extension JetpackConnectionRegisterResult: Sendable {}
#endif


extension JetpackConnectionRegisterResult: Equatable, Hashable {
    public static func ==(lhs: JetpackConnectionRegisterResult, rhs: JetpackConnectionRegisterResult) -> Bool {
        if lhs.authorizeUrl != rhs.authorizeUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(authorizeUrl)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionRegisterResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionRegisterResult {
        return
            try JetpackConnectionRegisterResult(
                authorizeUrl: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackConnectionRegisterResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.authorizeUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRegisterResult_lift(_ buf: RustBuffer) throws -> JetpackConnectionRegisterResult {
    return try FfiConverterTypeJetpackConnectionRegisterResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRegisterResult_lower(_ value: JetpackConnectionRegisterResult) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionRegisterResult.lower(value)
}


public struct JetpackConnectionUser {
    public let id: UserId
    public let username: String
    public let isConnected: Bool
    public let isMaster: Bool
    public let blogId: WpComSiteId?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UserId, username: String, isConnected: Bool, isMaster: Bool, blogId: WpComSiteId?) {
        self.id = id
        self.username = username
        self.isConnected = isConnected
        self.isMaster = isMaster
        self.blogId = blogId
    }
}

#if compiler(>=6)
extension JetpackConnectionUser: Sendable {}
#endif


extension JetpackConnectionUser: Equatable, Hashable {
    public static func ==(lhs: JetpackConnectionUser, rhs: JetpackConnectionUser) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.username != rhs.username {
            return false
        }
        if lhs.isConnected != rhs.isConnected {
            return false
        }
        if lhs.isMaster != rhs.isMaster {
            return false
        }
        if lhs.blogId != rhs.blogId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(username)
        hasher.combine(isConnected)
        hasher.combine(isMaster)
        hasher.combine(blogId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionUser: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionUser {
        return
            try JetpackConnectionUser(
                id: FfiConverterTypeUserId.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                isConnected: FfiConverterBool.read(from: &buf), 
                isMaster: FfiConverterBool.read(from: &buf), 
                blogId: FfiConverterOptionTypeWpComSiteId.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackConnectionUser, into buf: inout [UInt8]) {
        FfiConverterTypeUserId.write(value.id, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterBool.write(value.isConnected, into: &buf)
        FfiConverterBool.write(value.isMaster, into: &buf)
        FfiConverterOptionTypeWpComSiteId.write(value.blogId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionUser_lift(_ buf: RustBuffer) throws -> JetpackConnectionUser {
    return try FfiConverterTypeJetpackConnectionUser.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionUser_lower(_ value: JetpackConnectionUser) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionUser.lower(value)
}


public struct JetpackRemoteProvisionParams {

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init() {
    }
}

#if compiler(>=6)
extension JetpackRemoteProvisionParams: Sendable {}
#endif


extension JetpackRemoteProvisionParams: Equatable, Hashable {
    public static func ==(lhs: JetpackRemoteProvisionParams, rhs: JetpackRemoteProvisionParams) -> Bool {
        return true
    }

    public func hash(into hasher: inout Hasher) {
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackRemoteProvisionParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackRemoteProvisionParams {
        return
            JetpackRemoteProvisionParams()
    }

    public static func write(_ value: JetpackRemoteProvisionParams, into buf: inout [UInt8]) {
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteProvisionParams_lift(_ buf: RustBuffer) throws -> JetpackRemoteProvisionParams {
    return try FfiConverterTypeJetpackRemoteProvisionParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteProvisionParams_lower(_ value: JetpackRemoteProvisionParams) -> RustBuffer {
    return FfiConverterTypeJetpackRemoteProvisionParams.lower(value)
}


public struct JetpackRemoteProvisionResult {
    public let jpVersion: String
    public let redirectUri: String
    public let userId: UserId
    public let userEmail: String
    public let userLogin: String
    public let scope: String
    public let secret: String
    public let isActive: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(jpVersion: String, redirectUri: String, userId: UserId, userEmail: String, userLogin: String, scope: String, secret: String, isActive: Bool) {
        self.jpVersion = jpVersion
        self.redirectUri = redirectUri
        self.userId = userId
        self.userEmail = userEmail
        self.userLogin = userLogin
        self.scope = scope
        self.secret = secret
        self.isActive = isActive
    }
}

#if compiler(>=6)
extension JetpackRemoteProvisionResult: Sendable {}
#endif


extension JetpackRemoteProvisionResult: Equatable, Hashable {
    public static func ==(lhs: JetpackRemoteProvisionResult, rhs: JetpackRemoteProvisionResult) -> Bool {
        if lhs.jpVersion != rhs.jpVersion {
            return false
        }
        if lhs.redirectUri != rhs.redirectUri {
            return false
        }
        if lhs.userId != rhs.userId {
            return false
        }
        if lhs.userEmail != rhs.userEmail {
            return false
        }
        if lhs.userLogin != rhs.userLogin {
            return false
        }
        if lhs.scope != rhs.scope {
            return false
        }
        if lhs.secret != rhs.secret {
            return false
        }
        if lhs.isActive != rhs.isActive {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(jpVersion)
        hasher.combine(redirectUri)
        hasher.combine(userId)
        hasher.combine(userEmail)
        hasher.combine(userLogin)
        hasher.combine(scope)
        hasher.combine(secret)
        hasher.combine(isActive)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackRemoteProvisionResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackRemoteProvisionResult {
        return
            try JetpackRemoteProvisionResult(
                jpVersion: FfiConverterString.read(from: &buf), 
                redirectUri: FfiConverterString.read(from: &buf), 
                userId: FfiConverterTypeUserId.read(from: &buf), 
                userEmail: FfiConverterString.read(from: &buf), 
                userLogin: FfiConverterString.read(from: &buf), 
                scope: FfiConverterString.read(from: &buf), 
                secret: FfiConverterString.read(from: &buf), 
                isActive: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackRemoteProvisionResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.jpVersion, into: &buf)
        FfiConverterString.write(value.redirectUri, into: &buf)
        FfiConverterTypeUserId.write(value.userId, into: &buf)
        FfiConverterString.write(value.userEmail, into: &buf)
        FfiConverterString.write(value.userLogin, into: &buf)
        FfiConverterString.write(value.scope, into: &buf)
        FfiConverterString.write(value.secret, into: &buf)
        FfiConverterBool.write(value.isActive, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteProvisionResult_lift(_ buf: RustBuffer) throws -> JetpackRemoteProvisionResult {
    return try FfiConverterTypeJetpackRemoteProvisionResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteProvisionResult_lower(_ value: JetpackRemoteProvisionResult) -> RustBuffer {
    return FfiConverterTypeJetpackRemoteProvisionResult.lower(value)
}


public enum JetpackConnectionClientError: Swift.Error {

    
    
    case BlogIdMissing(url: String
    )
    case UserConnectionFailed(message: String
    )
    case Unhandled(WpApiError
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionClientError: FfiConverterRustBuffer {
    typealias SwiftType = JetpackConnectionClientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionClientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .BlogIdMissing(
            url: try FfiConverterString.read(from: &buf)
            )
        case 2: return .UserConnectionFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Unhandled(
            try FfiConverterTypeWpApiError.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: JetpackConnectionClientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .BlogIdMissing(url):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(url, into: &buf)
            
        
        case let .UserConnectionFailed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Unhandled(v1):
            writeInt(&buf, Int32(3))
            FfiConverterTypeWpApiError.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionClientError_lift(_ buf: RustBuffer) throws -> JetpackConnectionClientError {
    return try FfiConverterTypeJetpackConnectionClientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionClientError_lower(_ value: JetpackConnectionClientError) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionClientError.lower(value)
}


extension JetpackConnectionClientError: Equatable, Hashable {}



extension JetpackConnectionClientError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum JetpackConnectionStatus {
    
    case notConnected
    case site(blogId: WpComSiteId
    )
    case user(ownerSiteUsername: String, blogId: WpComSiteId
    )
}


#if compiler(>=6)
extension JetpackConnectionStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionStatus: FfiConverterRustBuffer {
    typealias SwiftType = JetpackConnectionStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .notConnected
        
        case 2: return .site(blogId: try FfiConverterTypeWpComSiteId.read(from: &buf)
        )
        
        case 3: return .user(ownerSiteUsername: try FfiConverterString.read(from: &buf), blogId: try FfiConverterTypeWpComSiteId.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: JetpackConnectionStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .notConnected:
            writeInt(&buf, Int32(1))
        
        
        case let .site(blogId):
            writeInt(&buf, Int32(2))
            FfiConverterTypeWpComSiteId.write(blogId, into: &buf)
            
        
        case let .user(ownerSiteUsername,blogId):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(ownerSiteUsername, into: &buf)
            FfiConverterTypeWpComSiteId.write(blogId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionStatus_lift(_ buf: RustBuffer) throws -> JetpackConnectionStatus {
    return try FfiConverterTypeJetpackConnectionStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionStatus_lower(_ value: JetpackConnectionStatus) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionStatus.lower(value)
}


extension JetpackConnectionStatus: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeWpComSiteId: FfiConverterRustBuffer {
    typealias SwiftType = WpComSiteId?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeWpComSiteId.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeWpComSiteId.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureJetpackInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func parseAsConnectionRequestConnectionCheckResponse(response: WpNetworkResponse)throws  -> ConnectionRequestConnectionCheckResponse  {
    return try  FfiConverterTypeConnectionRequestConnectionCheckResponse_lift(try rustCallWithError(FfiConverterTypeWpApiError_lift) {
    uniffi_jetpack_fn_func_parse_as_connection_request_connection_check_response(
        FfiConverterTypeWpNetworkResponse_lower(response),$0
    )
})
}
public func parseAsConnectionRequestConnectionDataResponse(response: WpNetworkResponse)throws  -> ConnectionRequestConnectionDataResponse  {
    return try  FfiConverterTypeConnectionRequestConnectionDataResponse_lift(try rustCallWithError(FfiConverterTypeWpApiError_lift) {
    uniffi_jetpack_fn_func_parse_as_connection_request_connection_data_response(
        FfiConverterTypeWpNetworkResponse_lower(response),$0
    )
})
}
public func parseAsConnectionRequestConnectionResponse(response: WpNetworkResponse)throws  -> ConnectionRequestConnectionResponse  {
    return try  FfiConverterTypeConnectionRequestConnectionResponse_lift(try rustCallWithError(FfiConverterTypeWpApiError_lift) {
    uniffi_jetpack_fn_func_parse_as_connection_request_connection_response(
        FfiConverterTypeWpNetworkResponse_lower(response),$0
    )
})
}
public func parseAsConnectionRequestRegisterResponse(response: WpNetworkResponse)throws  -> ConnectionRequestRegisterResponse  {
    return try  FfiConverterTypeConnectionRequestRegisterResponse_lift(try rustCallWithError(FfiConverterTypeWpApiError_lift) {
    uniffi_jetpack_fn_func_parse_as_connection_request_register_response(
        FfiConverterTypeWpNetworkResponse_lower(response),$0
    )
})
}
public func parseAsConnectionRequestRemoteProvisionResponse(response: WpNetworkResponse)throws  -> ConnectionRequestRemoteProvisionResponse  {
    return try  FfiConverterTypeConnectionRequestRemoteProvisionResponse_lift(try rustCallWithError(FfiConverterTypeWpApiError_lift) {
    uniffi_jetpack_fn_func_parse_as_connection_request_remote_provision_response(
        FfiConverterTypeWpNetworkResponse_lower(response),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_jetpack_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_jetpack_checksum_func_parse_as_connection_request_connection_check_response() != 40878) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_func_parse_as_connection_request_connection_data_response() != 43249) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_func_parse_as_connection_request_connection_response() != 36027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_func_parse_as_connection_request_register_response() != 64717) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_func_parse_as_connection_request_remote_provision_response() != 58238) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestbuilder_connection() != 46554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestbuilder_connection_check() != 31761) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestbuilder_connection_data() != 49200) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestbuilder_register() != 54907) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestbuilder_remote_provision() != 34625) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestexecutor_connection() != 6955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestexecutor_connection_check() != 65254) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestexecutor_connection_data() != 64565) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestexecutor_fetch_authentication_state() != 43655) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestexecutor_register() != 5443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_connectionrequestexecutor_remote_provision() != 28477) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_jetpackconnectionclient_connect_site() != 55604) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_jetpackconnectionclient_connect_user() != 14949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_jetpackconnectionclient_status() != 31312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_uniffijetpackapiclient_connection() != 936) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_method_uniffijetpackapirequestbuilder_connection() != 56353) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_constructor_jetpackconnectionclient_new() != 60063) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_constructor_uniffijetpackapiclient_new() != 14564) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jetpack_checksum_constructor_uniffijetpackapirequestbuilder_new() != 26476) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiEnsureWpApiInitialized()
    uniffiEnsureWpComInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureJetpackInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all