// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(libwordpressFFI)
import libwordpressFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_wp_com_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_wp_com_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureWpComInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol JetpackConnectionRequestBuilderProtocol: AnyObject, Sendable {
    
    func remoteConnectUser(wpComSiteId: WpComSiteId, params: JetpackRemoteConnectionParams)  -> WpNetworkRequest
    
}
open class JetpackConnectionRequestBuilder: JetpackConnectionRequestBuilderProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_wp_com_fn_clone_jetpackconnectionrequestbuilder(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_wp_com_fn_free_jetpackconnectionrequestbuilder(pointer, $0) }
    }

    

    
open func remoteConnectUser(wpComSiteId: WpComSiteId, params: JetpackRemoteConnectionParams) -> WpNetworkRequest  {
    return try!  FfiConverterTypeWpNetworkRequest_lift(try! rustCall() {
    uniffi_wp_com_fn_method_jetpackconnectionrequestbuilder_remote_connect_user(self.uniffiClonePointer(),
        FfiConverterTypeWpComSiteId_lower(wpComSiteId),
        FfiConverterTypeJetpackRemoteConnectionParams_lower(params),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionRequestBuilder: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = JetpackConnectionRequestBuilder

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> JetpackConnectionRequestBuilder {
        return JetpackConnectionRequestBuilder(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: JetpackConnectionRequestBuilder) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionRequestBuilder {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: JetpackConnectionRequestBuilder, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRequestBuilder_lift(_ pointer: UnsafeMutableRawPointer) throws -> JetpackConnectionRequestBuilder {
    return try FfiConverterTypeJetpackConnectionRequestBuilder.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRequestBuilder_lower(_ value: JetpackConnectionRequestBuilder) -> UnsafeMutableRawPointer {
    return FfiConverterTypeJetpackConnectionRequestBuilder.lower(value)
}






public protocol JetpackConnectionRequestExecutorProtocol: AnyObject, Sendable {
    
    func remoteConnectUser(wpComSiteId: WpComSiteId, params: JetpackRemoteConnectionParams) async throws  -> JetpackConnectionRequestRemoteConnectUserResponse
    
}
open class JetpackConnectionRequestExecutor: JetpackConnectionRequestExecutorProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_wp_com_fn_clone_jetpackconnectionrequestexecutor(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_wp_com_fn_free_jetpackconnectionrequestexecutor(pointer, $0) }
    }

    

    
open func remoteConnectUser(wpComSiteId: WpComSiteId, params: JetpackRemoteConnectionParams)async throws  -> JetpackConnectionRequestRemoteConnectUserResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_wp_com_fn_method_jetpackconnectionrequestexecutor_remote_connect_user(
                    self.uniffiClonePointer(),
                    FfiConverterTypeWpComSiteId_lower(wpComSiteId),FfiConverterTypeJetpackRemoteConnectionParams_lower(params)
                )
            },
            pollFunc: ffi_wp_com_rust_future_poll_rust_buffer,
            completeFunc: ffi_wp_com_rust_future_complete_rust_buffer,
            freeFunc: ffi_wp_com_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeJetpackConnectionRequestRemoteConnectUserResponse_lift,
            errorHandler: FfiConverterTypeWpApiError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionRequestExecutor: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = JetpackConnectionRequestExecutor

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> JetpackConnectionRequestExecutor {
        return JetpackConnectionRequestExecutor(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: JetpackConnectionRequestExecutor) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionRequestExecutor {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: JetpackConnectionRequestExecutor, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRequestExecutor_lift(_ pointer: UnsafeMutableRawPointer) throws -> JetpackConnectionRequestExecutor {
    return try FfiConverterTypeJetpackConnectionRequestExecutor.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRequestExecutor_lower(_ value: JetpackConnectionRequestExecutor) -> UnsafeMutableRawPointer {
    return FfiConverterTypeJetpackConnectionRequestExecutor.lower(value)
}






public protocol UniffiWpComApiClientProtocol: AnyObject, Sendable {
    
    func jetpackConnection()  -> JetpackConnectionRequestExecutor
    
}
open class UniffiWpComApiClient: UniffiWpComApiClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_wp_com_fn_clone_uniffiwpcomapiclient(self.pointer, $0) }
    }
public convenience init(authentication: WpAuthentication, requestExecutor: RequestExecutor) {
    let pointer =
        try! rustCall() {
    uniffi_wp_com_fn_constructor_uniffiwpcomapiclient_new(
        FfiConverterTypeWpAuthentication_lower(authentication),
        FfiConverterTypeRequestExecutor_lower(requestExecutor),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_wp_com_fn_free_uniffiwpcomapiclient(pointer, $0) }
    }

    

    
open func jetpackConnection() -> JetpackConnectionRequestExecutor  {
    return try!  FfiConverterTypeJetpackConnectionRequestExecutor_lift(try! rustCall() {
    uniffi_wp_com_fn_method_uniffiwpcomapiclient_jetpack_connection(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUniffiWpComApiClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = UniffiWpComApiClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiWpComApiClient {
        return UniffiWpComApiClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: UniffiWpComApiClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UniffiWpComApiClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: UniffiWpComApiClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiWpComApiClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiWpComApiClient {
    return try FfiConverterTypeUniffiWpComApiClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiWpComApiClient_lower(_ value: UniffiWpComApiClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeUniffiWpComApiClient.lower(value)
}






public protocol UniffiWpComApiRequestBuilderProtocol: AnyObject, Sendable {
    
    func jetpackConnection()  -> JetpackConnectionRequestBuilder
    
}
open class UniffiWpComApiRequestBuilder: UniffiWpComApiRequestBuilderProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_wp_com_fn_clone_uniffiwpcomapirequestbuilder(self.pointer, $0) }
    }
public convenience init(apiRootUrl: ParsedUrl, authentication: WpAuthentication) {
    let pointer =
        try! rustCall() {
    uniffi_wp_com_fn_constructor_uniffiwpcomapirequestbuilder_new(
        FfiConverterTypeParsedUrl_lower(apiRootUrl),
        FfiConverterTypeWpAuthentication_lower(authentication),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_wp_com_fn_free_uniffiwpcomapirequestbuilder(pointer, $0) }
    }

    

    
open func jetpackConnection() -> JetpackConnectionRequestBuilder  {
    return try!  FfiConverterTypeJetpackConnectionRequestBuilder_lift(try! rustCall() {
    uniffi_wp_com_fn_method_uniffiwpcomapirequestbuilder_jetpack_connection(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUniffiWpComApiRequestBuilder: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = UniffiWpComApiRequestBuilder

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiWpComApiRequestBuilder {
        return UniffiWpComApiRequestBuilder(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: UniffiWpComApiRequestBuilder) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UniffiWpComApiRequestBuilder {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: UniffiWpComApiRequestBuilder, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiWpComApiRequestBuilder_lift(_ pointer: UnsafeMutableRawPointer) throws -> UniffiWpComApiRequestBuilder {
    return try FfiConverterTypeUniffiWpComApiRequestBuilder.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUniffiWpComApiRequestBuilder_lower(_ value: UniffiWpComApiRequestBuilder) -> UnsafeMutableRawPointer {
    return FfiConverterTypeUniffiWpComApiRequestBuilder.lower(value)
}




public struct JetpackConnectionRequestRemoteConnectUserResponse {
    public let data: JetpackRemoteConnectionResult
    public let headerMap: WpNetworkHeaderMap

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(data: JetpackRemoteConnectionResult, headerMap: WpNetworkHeaderMap) {
        self.data = data
        self.headerMap = headerMap
    }
}

#if compiler(>=6)
extension JetpackConnectionRequestRemoteConnectUserResponse: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackConnectionRequestRemoteConnectUserResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackConnectionRequestRemoteConnectUserResponse {
        return
            try JetpackConnectionRequestRemoteConnectUserResponse(
                data: FfiConverterTypeJetpackRemoteConnectionResult.read(from: &buf), 
                headerMap: FfiConverterTypeWpNetworkHeaderMap.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackConnectionRequestRemoteConnectUserResponse, into buf: inout [UInt8]) {
        FfiConverterTypeJetpackRemoteConnectionResult.write(value.data, into: &buf)
        FfiConverterTypeWpNetworkHeaderMap.write(value.headerMap, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRequestRemoteConnectUserResponse_lift(_ buf: RustBuffer) throws -> JetpackConnectionRequestRemoteConnectUserResponse {
    return try FfiConverterTypeJetpackConnectionRequestRemoteConnectUserResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackConnectionRequestRemoteConnectUserResponse_lower(_ value: JetpackConnectionRequestRemoteConnectUserResponse) -> RustBuffer {
    return FfiConverterTypeJetpackConnectionRequestRemoteConnectUserResponse.lower(value)
}


public struct JetpackRemoteConnectionParams {
    /**
     * The value returned by `remote_provision`` endpoint
     */
    public let secret: String
    /**
     * Tthe value returned by remote_provision endpoint
     */
    public let scope: String
    /**
     * User ID from the Jetpack site
     */
    public let externalUserId: String
    /**
     * The Jetpack site URL
     */
    public let redirectUri: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The value returned by `remote_provision`` endpoint
         */secret: String, 
        /**
         * Tthe value returned by remote_provision endpoint
         */scope: String, 
        /**
         * User ID from the Jetpack site
         */externalUserId: String, 
        /**
         * The Jetpack site URL
         */redirectUri: String) {
        self.secret = secret
        self.scope = scope
        self.externalUserId = externalUserId
        self.redirectUri = redirectUri
    }
}

#if compiler(>=6)
extension JetpackRemoteConnectionParams: Sendable {}
#endif


extension JetpackRemoteConnectionParams: Equatable, Hashable {
    public static func ==(lhs: JetpackRemoteConnectionParams, rhs: JetpackRemoteConnectionParams) -> Bool {
        if lhs.secret != rhs.secret {
            return false
        }
        if lhs.scope != rhs.scope {
            return false
        }
        if lhs.externalUserId != rhs.externalUserId {
            return false
        }
        if lhs.redirectUri != rhs.redirectUri {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(secret)
        hasher.combine(scope)
        hasher.combine(externalUserId)
        hasher.combine(redirectUri)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackRemoteConnectionParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackRemoteConnectionParams {
        return
            try JetpackRemoteConnectionParams(
                secret: FfiConverterString.read(from: &buf), 
                scope: FfiConverterString.read(from: &buf), 
                externalUserId: FfiConverterString.read(from: &buf), 
                redirectUri: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackRemoteConnectionParams, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secret, into: &buf)
        FfiConverterString.write(value.scope, into: &buf)
        FfiConverterString.write(value.externalUserId, into: &buf)
        FfiConverterString.write(value.redirectUri, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteConnectionParams_lift(_ buf: RustBuffer) throws -> JetpackRemoteConnectionParams {
    return try FfiConverterTypeJetpackRemoteConnectionParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteConnectionParams_lower(_ value: JetpackRemoteConnectionParams) -> RustBuffer {
    return FfiConverterTypeJetpackRemoteConnectionParams.lower(value)
}


public struct JetpackRemoteConnectionResult {
    public let code: String
    public let message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(code: String, message: String) {
        self.code = code
        self.message = message
    }
}

#if compiler(>=6)
extension JetpackRemoteConnectionResult: Sendable {}
#endif


extension JetpackRemoteConnectionResult: Equatable, Hashable {
    public static func ==(lhs: JetpackRemoteConnectionResult, rhs: JetpackRemoteConnectionResult) -> Bool {
        if lhs.code != rhs.code {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(code)
        hasher.combine(message)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJetpackRemoteConnectionResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JetpackRemoteConnectionResult {
        return
            try JetpackRemoteConnectionResult(
                code: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: JetpackRemoteConnectionResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.code, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteConnectionResult_lift(_ buf: RustBuffer) throws -> JetpackRemoteConnectionResult {
    return try FfiConverterTypeJetpackRemoteConnectionResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJetpackRemoteConnectionResult_lower(_ value: JetpackRemoteConnectionResult) -> RustBuffer {
    return FfiConverterTypeJetpackRemoteConnectionResult.lower(value)
}


/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias WpComSiteId = UInt64

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWpComSiteId: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WpComSiteId {
        return try FfiConverterUInt64.read(from: &buf)
    }

    public static func write(_ value: WpComSiteId, into buf: inout [UInt8]) {
        return FfiConverterUInt64.write(value, into: &buf)
    }

    public static func lift(_ value: UInt64) throws -> WpComSiteId {
        return try FfiConverterUInt64.lift(value)
    }

    public static func lower(_ value: WpComSiteId) -> UInt64 {
        return FfiConverterUInt64.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWpComSiteId_lift(_ value: UInt64) throws -> WpComSiteId {
    return try FfiConverterTypeWpComSiteId.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWpComSiteId_lower(_ value: WpComSiteId) -> UInt64 {
    return FfiConverterTypeWpComSiteId.lower(value)
}

private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureWpComInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func parseAsJetpackConnectionRequestRemoteConnectUserResponse(response: WpNetworkResponse)throws  -> JetpackConnectionRequestRemoteConnectUserResponse  {
    return try  FfiConverterTypeJetpackConnectionRequestRemoteConnectUserResponse_lift(try rustCallWithError(FfiConverterTypeWpApiError_lift) {
    uniffi_wp_com_fn_func_parse_as_jetpack_connection_request_remote_connect_user_response(
        FfiConverterTypeWpNetworkResponse_lower(response),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_wp_com_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_wp_com_checksum_func_parse_as_jetpack_connection_request_remote_connect_user_response() != 24874) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_com_checksum_method_jetpackconnectionrequestbuilder_remote_connect_user() != 7966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_com_checksum_method_jetpackconnectionrequestexecutor_remote_connect_user() != 39706) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_com_checksum_method_uniffiwpcomapiclient_jetpack_connection() != 315) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_com_checksum_method_uniffiwpcomapirequestbuilder_jetpack_connection() != 3996) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_com_checksum_constructor_uniffiwpcomapiclient_new() != 7939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_com_checksum_constructor_uniffiwpcomapirequestbuilder_new() != 5690) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiEnsureWpApiInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureWpComInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all