// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(libwordpressFFI)
import libwordpressFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_wp_mobile_cache_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_wp_mobile_cache_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureWpMobileCacheInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol DatabaseDelegate: AnyObject, Sendable {
    
    func didUpdate(updateHook: UpdateHook) 
    
}
open class DatabaseDelegateImpl: DatabaseDelegate, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wp_mobile_cache_fn_clone_databasedelegate(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wp_mobile_cache_fn_free_databasedelegate(handle, $0) }
    }

    

    
open func didUpdate(updateHook: UpdateHook)  {try! rustCall() {
    uniffi_wp_mobile_cache_fn_method_databasedelegate_did_update(
            self.uniffiCloneHandle(),
        FfiConverterTypeUpdateHook_lower(updateHook),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceDatabaseDelegate {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceDatabaseDelegate = UniffiVTableCallbackInterfaceDatabaseDelegate(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeDatabaseDelegate.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface DatabaseDelegate: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeDatabaseDelegate.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface DatabaseDelegate: handle missing in uniffiClone")
            }
        },
        didUpdate: { (
            uniffiHandle: UInt64,
            updateHook: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeDatabaseDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.didUpdate(
                     updateHook: try FfiConverterTypeUpdateHook_lift(updateHook)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceDatabaseDelegate> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceDatabaseDelegate>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitDatabaseDelegate() {
    uniffi_wp_mobile_cache_fn_init_callback_vtable_databasedelegate(UniffiCallbackInterfaceDatabaseDelegate.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDatabaseDelegate: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<DatabaseDelegate>()

    typealias FfiType = UInt64
    typealias SwiftType = DatabaseDelegate

    public static func lift(_ handle: UInt64) throws -> DatabaseDelegate {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return DatabaseDelegateImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: DatabaseDelegate) -> UInt64 {
         if let rustImpl = value as? DatabaseDelegateImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DatabaseDelegate {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DatabaseDelegate, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatabaseDelegate_lift(_ handle: UInt64) throws -> DatabaseDelegate {
    return try FfiConverterTypeDatabaseDelegate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDatabaseDelegate_lower(_ value: DatabaseDelegate) -> UInt64 {
    return FfiConverterTypeDatabaseDelegate.lower(value)
}






public protocol WpApiCacheProtocol: AnyObject, Sendable {
    
    func performMigrations() throws  -> Int64
    
    /**
     * Remove a self-hosted site and all its cached data from the database.
     *
     * Returns `true` if the site was found and removed, `false` if no site
     * with the given URL exists.
     */
    func removeSelfHostedSite(url: ParsedUrl) throws  -> Bool
    
    /**
     * Remove a WordPress.com site and all its cached data from the database.
     *
     * Returns `true` if the site was found and removed, `false` if no site
     * with the given site ID exists.
     */
    func removeWordpressComSite(siteId: WpComSiteId) throws  -> Bool
    
    func startListeningForUpdates(delegate: DatabaseDelegate) 
    
    func stopListeningForUpdates() 
    
}
open class WpApiCache: WpApiCacheProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wp_mobile_cache_fn_clone_wpapicache(self.handle, $0) }
    }
public convenience init(path: String?)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeSqliteDbError_lift) {
    uniffi_wp_mobile_cache_fn_constructor_wpapicache_new(
        FfiConverterOptionString.lower(path),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wp_mobile_cache_fn_free_wpapicache(handle, $0) }
    }

    

    
open func performMigrations()throws  -> Int64  {
    return try  FfiConverterInt64.lift(try rustCallWithError(FfiConverterTypeSqliteDbError_lift) {
    uniffi_wp_mobile_cache_fn_method_wpapicache_perform_migrations(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Remove a self-hosted site and all its cached data from the database.
     *
     * Returns `true` if the site was found and removed, `false` if no site
     * with the given URL exists.
     */
open func removeSelfHostedSite(url: ParsedUrl)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSqliteDbError_lift) {
    uniffi_wp_mobile_cache_fn_method_wpapicache_remove_self_hosted_site(
            self.uniffiCloneHandle(),
        FfiConverterTypeParsedUrl_lower(url),$0
    )
})
}
    
    /**
     * Remove a WordPress.com site and all its cached data from the database.
     *
     * Returns `true` if the site was found and removed, `false` if no site
     * with the given site ID exists.
     */
open func removeWordpressComSite(siteId: WpComSiteId)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSqliteDbError_lift) {
    uniffi_wp_mobile_cache_fn_method_wpapicache_remove_wordpress_com_site(
            self.uniffiCloneHandle(),
        FfiConverterTypeWpComSiteId_lower(siteId),$0
    )
})
}
    
open func startListeningForUpdates(delegate: DatabaseDelegate)  {try! rustCall() {
    uniffi_wp_mobile_cache_fn_method_wpapicache_start_listening_for_updates(
            self.uniffiCloneHandle(),
        FfiConverterTypeDatabaseDelegate_lower(delegate),$0
    )
}
}
    
open func stopListeningForUpdates()  {try! rustCall() {
    uniffi_wp_mobile_cache_fn_method_wpapicache_stop_listening_for_updates(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWpApiCache: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WpApiCache

    public static func lift(_ handle: UInt64) throws -> WpApiCache {
        return WpApiCache(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WpApiCache) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WpApiCache {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WpApiCache, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWpApiCache_lift(_ handle: UInt64) throws -> WpApiCache {
    return try FfiConverterTypeWpApiCache.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWpApiCache_lower(_ value: WpApiCache) -> UInt64 {
    return FfiConverterTypeWpApiCache.lower(value)
}




/**
 * Represents a cached WordPress site in the database.
 *
 * # Design Rationale
 *
 * This is intentionally a database-specific type (hence the `Db` prefix) rather than
 * a domain type representing a WordPress site. This design choice prevents confusion:
 *
 * - **Not a WordPress.com site ID**: The `row_id` has no relationship to WordPress.com site IDs
 * - **Not a self-hosted site identifier**: Self-hosted sites don't have numeric IDs
 * - **Internal cache identifier only**: This ID exists only for our local database's multi-site support
 *
 * # Site Type Mapping
 *
 * The `site_type` field indicates which type-specific table contains additional data:
 * - `DbSiteType::SelfHosted` → `mapped_site_id` references `self_hosted_sites` table
 * - `DbSiteType::WordPressCom` → `mapped_site_id` references `wordpress_com_sites` table (future)
 *
 * Note: `mapped_site_id` is a reference column, not a foreign key constraint, since it can
 * point to different tables based on `site_type`.
 */
public struct DbSite: Equatable, Hashable {
    public let rowId: RowId
    public let siteType: DbSiteType
    public let mappedSiteId: RowId

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rowId: RowId, siteType: DbSiteType, mappedSiteId: RowId) {
        self.rowId = rowId
        self.siteType = siteType
        self.mappedSiteId = mappedSiteId
    }

    

    
}

#if compiler(>=6)
extension DbSite: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDbSite: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DbSite {
        return
            try DbSite(
                rowId: FfiConverterTypeRowId.read(from: &buf), 
                siteType: FfiConverterTypeDbSiteType.read(from: &buf), 
                mappedSiteId: FfiConverterTypeRowId.read(from: &buf)
        )
    }

    public static func write(_ value: DbSite, into buf: inout [UInt8]) {
        FfiConverterTypeRowId.write(value.rowId, into: &buf)
        FfiConverterTypeDbSiteType.write(value.siteType, into: &buf)
        FfiConverterTypeRowId.write(value.mappedSiteId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDbSite_lift(_ buf: RustBuffer) throws -> DbSite {
    return try FfiConverterTypeDbSite.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDbSite_lower(_ value: DbSite) -> RustBuffer {
    return FfiConverterTypeDbSite.lower(value)
}


/**
 * Unique identifier for an entity stored in the cache database
 *
 * Encapsulates the complete identity of a cached entity:
 * - Which site (DbSite with site_type and mapped_site_id)
 * - Which table (DbTable enum variant)
 * - Which row (rowid)
 *
 * This type serves as an opaque handle that can be used to:
 * - Create observable entities without database lookups
 * - Compare entities for identity equality
 * - Filter database change notifications
 * - Reload entity data via load_data() using the stored DbSite
 *
 * EntityId is immutable once created and remains valid even if the
 * underlying database row is deleted (though queries may return None).
 *
 * Note: This is a uniffi::Record (value type) which means it can be used
 * directly as a HashMap key in Kotlin/Swift without additional wrappers.
 */
public struct EntityId: Equatable, Hashable {
    /**
     * The site this entity belongs to
     */
    public let dbSite: DbSite
    /**
     * The table where this entity is stored
     */
    public let table: DbTable
    /**
     * The database rowid (SQLite autoincrement primary key)
     */
    public let rowid: RowId

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The site this entity belongs to
         */dbSite: DbSite, 
        /**
         * The table where this entity is stored
         */table: DbTable, 
        /**
         * The database rowid (SQLite autoincrement primary key)
         */rowid: RowId) {
        self.dbSite = dbSite
        self.table = table
        self.rowid = rowid
    }

    

    
}

#if compiler(>=6)
extension EntityId: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntityId: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntityId {
        return
            try EntityId(
                dbSite: FfiConverterTypeDbSite.read(from: &buf), 
                table: FfiConverterTypeDbTable.read(from: &buf), 
                rowid: FfiConverterTypeRowId.read(from: &buf)
        )
    }

    public static func write(_ value: EntityId, into buf: inout [UInt8]) {
        FfiConverterTypeDbSite.write(value.dbSite, into: &buf)
        FfiConverterTypeDbTable.write(value.table, into: &buf)
        FfiConverterTypeRowId.write(value.rowid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityId_lift(_ buf: RustBuffer) throws -> EntityId {
    return try FfiConverterTypeEntityId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityId_lower(_ value: EntityId) -> RustBuffer {
    return FfiConverterTypeEntityId.lower(value)
}


public struct UpdateHook: Equatable, Hashable {
    public let action: HookAction
    public let dbName: String
    public let table: DbTable
    public let rowId: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(action: HookAction, dbName: String, table: DbTable, rowId: Int64) {
        self.action = action
        self.dbName = dbName
        self.table = table
        self.rowId = rowId
    }

    

    
}

#if compiler(>=6)
extension UpdateHook: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUpdateHook: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UpdateHook {
        return
            try UpdateHook(
                action: FfiConverterTypeHookAction.read(from: &buf), 
                dbName: FfiConverterString.read(from: &buf), 
                table: FfiConverterTypeDbTable.read(from: &buf), 
                rowId: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: UpdateHook, into buf: inout [UInt8]) {
        FfiConverterTypeHookAction.write(value.action, into: &buf)
        FfiConverterString.write(value.dbName, into: &buf)
        FfiConverterTypeDbTable.write(value.table, into: &buf)
        FfiConverterInt64.write(value.rowId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUpdateHook_lift(_ buf: RustBuffer) throws -> UpdateHook {
    return try FfiConverterTypeUpdateHook.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUpdateHook_lower(_ value: UpdateHook) -> RustBuffer {
    return FfiConverterTypeUpdateHook.lower(value)
}


public struct User: Equatable, Hashable {
    public let id: Int64
    public let name: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, name: String) {
        self.id = id
        self.name = name
    }

    

    
}

#if compiler(>=6)
extension User: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUser: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> User {
        return
            try User(
                id: FfiConverterInt64.read(from: &buf), 
                name: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: User, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUser_lift(_ buf: RustBuffer) throws -> User {
    return try FfiConverterTypeUser.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUser_lower(_ value: User) -> RustBuffer {
    return FfiConverterTypeUser.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Type of WordPress site stored in the database.
 *
 * Uses integer representation in the database for performance.
 */

public enum DbSiteType: Int64, Equatable, Hashable {
    
    case selfHosted = 0
    case wordPressCom = 1





}

#if compiler(>=6)
extension DbSiteType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDbSiteType: FfiConverterRustBuffer {
    typealias SwiftType = DbSiteType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DbSiteType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .selfHosted
        
        case 2: return .wordPressCom
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DbSiteType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .selfHosted:
            writeInt(&buf, Int32(1))
        
        
        case .wordPressCom:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDbSiteType_lift(_ buf: RustBuffer) throws -> DbSiteType {
    return try FfiConverterTypeDbSiteType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDbSiteType_lower(_ value: DbSiteType) -> RustBuffer {
    return FfiConverterTypeDbSiteType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Database table identifier.
 *
 * Represents all tables tracked in the cache database. This enum provides
 * a single source of truth for table names, ensuring consistency across
 * the codebase and preventing typos.
 *
 * Note: uniffi::Enum makes this type available to platform bindings but
 * without exposing any methods (which is intentional - we don't want
 * Kotlin/Swift to access table names directly).
 */

public enum DbTable: Equatable, Hashable {
    
    /**
     * Posts with edit context (full data for editing)
     */
    case postsEditContext
    /**
     * Posts with view context (public viewing data)
     */
    case postsViewContext
    /**
     * Posts with embed context (minimal data for embeds)
     */
    case postsEmbedContext
    /**
     * Post types with edit context (post type configuration data)
     */
    case postTypesEditContext
    /**
     * Media with edit context (full media data for editing)
     */
    case mediaEditContext
    /**
     * Self-hosted WordPress sites
     */
    case selfHostedSites
    /**
     * Database sites mapping table
     */
    case dbSites
    /**
     * Term relationships (post-category, post-tag associations)
     */
    case termRelationships
    /**
     * List metadata headers (pagination, version)
     */
    case listMetadata
    /**
     * List metadata items (entity IDs with ordering)
     */
    case listMetadataItems
    /**
     * List metadata sync state (idle, fetching, error)
     */
    case listMetadataState
    /**
     * Entity state tracking (missing, fetching, cached, stale, failed)
     */
    case entityState
    /**
     * WordPress.com sites
     */
    case wordPressComSites





}

#if compiler(>=6)
extension DbTable: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDbTable: FfiConverterRustBuffer {
    typealias SwiftType = DbTable

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DbTable {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .postsEditContext
        
        case 2: return .postsViewContext
        
        case 3: return .postsEmbedContext
        
        case 4: return .postTypesEditContext
        
        case 5: return .mediaEditContext
        
        case 6: return .selfHostedSites
        
        case 7: return .dbSites
        
        case 8: return .termRelationships
        
        case 9: return .listMetadata
        
        case 10: return .listMetadataItems
        
        case 11: return .listMetadataState
        
        case 12: return .entityState
        
        case 13: return .wordPressComSites
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DbTable, into buf: inout [UInt8]) {
        switch value {
        
        
        case .postsEditContext:
            writeInt(&buf, Int32(1))
        
        
        case .postsViewContext:
            writeInt(&buf, Int32(2))
        
        
        case .postsEmbedContext:
            writeInt(&buf, Int32(3))
        
        
        case .postTypesEditContext:
            writeInt(&buf, Int32(4))
        
        
        case .mediaEditContext:
            writeInt(&buf, Int32(5))
        
        
        case .selfHostedSites:
            writeInt(&buf, Int32(6))
        
        
        case .dbSites:
            writeInt(&buf, Int32(7))
        
        
        case .termRelationships:
            writeInt(&buf, Int32(8))
        
        
        case .listMetadata:
            writeInt(&buf, Int32(9))
        
        
        case .listMetadataItems:
            writeInt(&buf, Int32(10))
        
        
        case .listMetadataState:
            writeInt(&buf, Int32(11))
        
        
        case .entityState:
            writeInt(&buf, Int32(12))
        
        
        case .wordPressComSites:
            writeInt(&buf, Int32(13))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDbTable_lift(_ buf: RustBuffer) throws -> DbTable {
    return try FfiConverterTypeDbTable.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDbTable_lower(_ value: DbTable) -> RustBuffer {
    return FfiConverterTypeDbTable.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Type-safe identifier for entity collections.
 *
 * Each variant represents a specific entity type with its context (e.g., posts in edit context).
 * This prevents arbitrary strings from being passed and ensures only valid entity types are used.
 *
 * Stored as INTEGER in the database via ToSql/FromSql implementations. The repr(i64) ensures
 * stable values even if the enum definition order changes.
 *
 * **IMPORTANT**: Do not change the integer values - they are persisted in the database.
 */

public enum EntityType: Int64, Equatable, Hashable {
    
    /**
     * Posts with edit context (table: posts_edit_context)
     */
    case postsEditContext = 0
    /**
     * Media with edit context (table: media_edit_context)
     */
    case mediaEditContext = 1





}

#if compiler(>=6)
extension EntityType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntityType: FfiConverterRustBuffer {
    typealias SwiftType = EntityType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntityType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .postsEditContext
        
        case 2: return .mediaEditContext
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EntityType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .postsEditContext:
            writeInt(&buf, Int32(1))
        
        
        case .mediaEditContext:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityType_lift(_ buf: RustBuffer) throws -> EntityType {
    return try FfiConverterTypeEntityType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityType_lower(_ value: EntityType) -> RustBuffer {
    return FfiConverterTypeEntityType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum HookAction: Equatable, Hashable {
    
    case insert
    case update
    case delete





}

#if compiler(>=6)
extension HookAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHookAction: FfiConverterRustBuffer {
    typealias SwiftType = HookAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HookAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .insert
        
        case 2: return .update
        
        case 3: return .delete
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HookAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .insert:
            writeInt(&buf, Int32(1))
        
        
        case .update:
            writeInt(&buf, Int32(2))
        
        
        case .delete:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHookAction_lift(_ buf: RustBuffer) throws -> HookAction {
    return try FfiConverterTypeHookAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHookAction_lower(_ value: HookAction) -> RustBuffer {
    return FfiConverterTypeHookAction.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Sync state for a list.
 *
 * Stored as INTEGER in the database. The repr(i64) ensures stable values
 * even if the enum definition order changes.
 */

public enum ListState: Int64, Equatable, Hashable {
    
    /**
     * No sync in progress
     */
    case idle = 0
    /**
     * Fetching first page (pull-to-refresh)
     */
    case fetchingFirstPage = 1
    /**
     * Fetching subsequent page (load more)
     */
    case fetchingNextPage = 2
    /**
     * Last sync failed
     */
    case error = 3





}

#if compiler(>=6)
extension ListState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeListState: FfiConverterRustBuffer {
    typealias SwiftType = ListState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .idle
        
        case 2: return .fetchingFirstPage
        
        case 3: return .fetchingNextPage
        
        case 4: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ListState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .idle:
            writeInt(&buf, Int32(1))
        
        
        case .fetchingFirstPage:
            writeInt(&buf, Int32(2))
        
        
        case .fetchingNextPage:
            writeInt(&buf, Int32(3))
        
        
        case .error:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListState_lift(_ buf: RustBuffer) throws -> ListState {
    return try FfiConverterTypeListState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListState_lower(_ value: ListState) -> RustBuffer {
    return FfiConverterTypeListState.lower(value)
}



public enum SqliteDbError: Swift.Error, Equatable, Hashable {

    
    
    case SqliteError(String
    )
    case ConstraintViolation(String
    )
    case TableNameMismatch(expected: DbTable, actual: DbTable
    )
    case PerPageMismatch(expected: Int64, actual: Int64
    )

    

    

    
}

#if compiler(>=6)
extension SqliteDbError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSqliteDbError: FfiConverterRustBuffer {
    typealias SwiftType = SqliteDbError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SqliteDbError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .SqliteError(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .ConstraintViolation(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .TableNameMismatch(
            expected: try FfiConverterTypeDbTable.read(from: &buf), 
            actual: try FfiConverterTypeDbTable.read(from: &buf)
            )
        case 4: return .PerPageMismatch(
            expected: try FfiConverterInt64.read(from: &buf), 
            actual: try FfiConverterInt64.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SqliteDbError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .SqliteError(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConstraintViolation(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .TableNameMismatch(expected,actual):
            writeInt(&buf, Int32(3))
            FfiConverterTypeDbTable.write(expected, into: &buf)
            FfiConverterTypeDbTable.write(actual, into: &buf)
            
        
        case let .PerPageMismatch(expected,actual):
            writeInt(&buf, Int32(4))
            FfiConverterInt64.write(expected, into: &buf)
            FfiConverterInt64.write(actual, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSqliteDbError_lift(_ buf: RustBuffer) throws -> SqliteDbError {
    return try FfiConverterTypeSqliteDbError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSqliteDbError_lower(_ value: SqliteDbError) -> RustBuffer {
    return FfiConverterTypeSqliteDbError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}


/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias RowId = Int64

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRowId: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RowId {
        return try FfiConverterInt64.read(from: &buf)
    }

    public static func write(_ value: RowId, into buf: inout [UInt8]) {
        return FfiConverterInt64.write(value, into: &buf)
    }

    public static func lift(_ value: Int64) throws -> RowId {
        return try FfiConverterInt64.lift(value)
    }

    public static func lower(_ value: RowId) -> Int64 {
        return FfiConverterInt64.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRowId_lift(_ value: Int64) throws -> RowId {
    return try FfiConverterTypeRowId.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRowId_lower(_ value: RowId) -> Int64 {
    return FfiConverterTypeRowId.lower(value)
}


private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_wp_mobile_cache_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_wp_mobile_cache_checksum_method_databasedelegate_did_update() != 34122) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_mobile_cache_checksum_method_wpapicache_perform_migrations() != 8437) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_mobile_cache_checksum_method_wpapicache_remove_self_hosted_site() != 31483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_mobile_cache_checksum_method_wpapicache_remove_wordpress_com_site() != 64010) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_mobile_cache_checksum_method_wpapicache_start_listening_for_updates() != 34766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_mobile_cache_checksum_method_wpapicache_stop_listening_for_updates() != 48424) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wp_mobile_cache_checksum_constructor_wpapicache_new() != 45058) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitDatabaseDelegate()
    uniffiEnsureWpApiInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureWpMobileCacheInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all