// A `TestCredentials::instance()` function will be generated by this
include!(concat!(env!("OUT_DIR"), "/generated_test_credentials.rs"));

#[derive(Debug, Default)]
pub struct TestCredentials {
    pub site_url: &'static str,
    pub admin_username: &'static str,
    pub admin_password: &'static str,
    pub admin_password_uuid: &'static str,
    pub admin_account_password: &'static str,
    pub subscriber_username: &'static str,
    pub subscriber_password: &'static str,
    pub subscriber_password_uuid: &'static str,
    pub author_username: &'static str,
    pub author_password: &'static str,
    pub password_protected_post_id: i64,
    pub password_protected_post_password: &'static str,
    pub password_protected_post_title: &'static str,
    pub password_protected_comment_id: i64,
    pub password_protected_comment_author: &'static str,
    pub trashed_post_id: i64,
    pub first_post_date_gmt: &'static str,
    pub wordpress_core_version: &'static str,
    pub integration_test_custom_template_id: &'static str,
    pub revisioned_post_id: i64,
    pub revision_id_for_revisioned_post_id: i64,
    pub autosaved_post_id: i64,
    pub autosave_id_for_autosaved_post_id: i64,
    pub password_protected_page_id: i64,
    pub password_protected_page_password: &'static str,
    pub password_protected_page_title: &'static str,
    pub trashed_page_id: i64,
    pub first_page_id: i64,
    pub revisioned_page_id: i64,
    pub revision_id_for_revisioned_page_id: i64,
    pub autosaved_page_id: i64,
    pub autosave_id_for_autosaved_page_id: i64,
    pub primary_menu_location: &'static str,
    pub footer_menu_location: &'static str,
    pub nav_menu_item_id: i64,
    pub autosave_id_for_nav_menu_item_id: i64,
    pub navigation_id: i64,
    pub revision_id_for_navigation_id: i64,
    pub autosaved_navigation_id: i64,
    pub autosave_id_for_autosaved_navigation_id: i64,
}

impl TestCredentials {
    pub fn date_format() -> &'static str {
        "%Y-%m-%d %H:%M:%S"
    }
}

#[derive(Debug, Default)]
pub struct WpComTestCredentials {
    pub bearer_token: &'static str,
    pub site_id: u64,
    pub wp_com_subscriber_user_id: i64,
    pub email_subscriber_subscription_id: u64,
    pub comment_id: i64,
    pub client_id: u64,
    pub client_secret: &'static str,
}
