[package]
name = "wordpress_org_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = [ "full" ] }
