[package]
name = "wp_api_integration_tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wp_api = { path = "../wp_api", features = [ "integration-tests" ] }

[dev-dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
paste = { workspace = true }
reqwest = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
tokio = { workspace = true, features = [ "full" ] }
serde_json = { workspace = true }
serial_test = { workspace = true }
sqlx = { workspace = true, features = [ "chrono", "mysql", "runtime-tokio", "tls-native-tls" ]}
