[bindings.kotlin]
android = false
android_cleaner = false
generate_immutable_records = true

[bindings.swift]
ffi_module_name = "libwordpressFFI"
ffi_module_filename = "jetpack_api_uniffi"
generate_module_map = false
generate_immutable_records = true
