[package]
name = "wp_com_e2e"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
libtest-mimic = "0.8"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true }
wp_api = { path = "../wp_api", features = [ "reqwest-request-executor" ] }

[[bin]]
name = "wp_com_e2e"
