[package]
name = "wp_api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_api"

[dependencies]
http = { workspace = true }
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1.0"
uniffi = { workspace = true }

[build-dependencies]
uniffi = { workspace = true , features = [ "build", "cli" ] }
