[package]
name = "wp_api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_api"

[dependencies]
base64 = { workspace = true }
http = { workspace = true }
url = "2.5"
parse_link_header = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uniffi = { workspace = true }
wp_derive = { path = "../wp_derive" }

[dev-dependencies]
rstest = { workspace = true }

[build-dependencies]
uniffi = { workspace = true , features = [ "build", "cli" ] }
