[package]
name = "wp_api"
version = "0.1.0"
edition = "2021"

[features]
integration-tests = []

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_api"

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
indoc = { workspace = true }
url = { workspace = true }
parse_link_header = { workspace = true }
paste = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
thiserror = { workspace = true }
uniffi = { workspace = true }
wp_contextual = { path = "../wp_contextual" }
wp_derive_request_builder = { path = "../wp_derive_request_builder", features = [ "generate_request_builder" ] }

[dev-dependencies]
uu_cp = "0.0.26"
rstest = { workspace = true }
rstest_reuse = { workspace = true }

[build-dependencies]
uniffi = { workspace = true , features = [ "build", "cli" ] }
