[bindings.kotlin]
android = false
android_cleaner = false
cdylib_name = "wp_mobile"
generate_immutable_records = true

[bindings.kotlin.custom_types.WpGmtDateTime]
type_name = "Date"
imports = ["java.util.Date", "java.time.Instant"]
into_custom = "Date.from(Instant.ofEpochSecond({}))"
from_custom = "{}.toInstant().epochSecond"

[bindings.swift.custom_types.WpGmtDateTime]
type_name = "Date"
imports = ["Foundation"]
into_custom = "Date(timeIntervalSince1970: TimeInterval({}))"
from_custom = "Int64({}.timeIntervalSince1970)"

[bindings.swift]
ffi_module_name = "libwordpressFFI"
ffi_module_filename = "wp_api_uniffi"
generate_module_map = false
generate_immutable_records = true
experimental_sendable_value_types = true
omit_localized_error_conformance = true
