[bindings.kotlin]
android = false
android_cleaner = false
cdylib_name = "wp_api"
generate_immutable_records = true

[bindings.swift]
ffi_module_name = "libwordpressFFI"
ffi_module_filename = "wp_api_uniffi.h"
generate_module_map = false
generate_immutable_records = true
