[package]
name = "wp_cli"
version = "0.1.0"
edition = "2021"
default-run = "wp_cli"

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
wp_api = { path = "../wp_api" }
wp_networking = { path = "../wp_networking" }
