[package]
name = "wp_cli"
version = "0.1.0"
edition = "2021"
default-run = "wp_cli"

[dependencies]
wp_api = { path = "../wp_api" }
wp_networking = { path = "../wp_networking" }
wp_parsing = { path = "../wp_parsing" }
