[package]
name = "wp_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
wp_serde_helper = { path = "../wp_serde_helper" }
