# frozen_string_literal: true

PROJECT_ROOT = File.expand_path('..', __dir__)

LANE_VALUE_VERSION = 'WP_VERSION'
LANE_VALUE_GITHUB_TOKEN = 'WP_GITHUB_TOKEN'
LANE_VALUE_XCFRAMEWORK = 'WP_XCFRAMEWORK'
LANE_VALUE_XCFRAMEWORK_CHECKSUM = 'WP_XCFRAMEWORK_CHECKSUM'

GITHUB_REPO = 'automattic/wordpress-rs'
GIT_REMOTE_NAME = 'origin'

lane :release do |options|
  version = options[:version] || UI.user_error!('version is required')
  lane_context[LANE_VALUE_VERSION] = version

  github_token = options[:github_token] || ENV['GITHUB_TOKEN'] || UI.user_error!('github_token is required')
  lane_context.set_sensitive(LANE_VALUE_GITHUB_TOKEN, github_token)

  validate
  build_xcframework
  update_swift_package
  publish_github_release
end

lane :validate do
  version = lane_context[LANE_VALUE_VERSION] || UI.user_error!('Missing version lane context')
  github_token = lane_context[LANE_VALUE_GITHUB_TOKEN] || UI.user_error!('Missing github token lane context')

  UI.user_error!("Release #{version} already exists in the GitHub repo") \
    unless get_github_release(url: GITHUB_REPO, version: version, api_token: github_token).nil?
  remove_lane_context_values [
    SharedValues::GITHUB_API_RESPONSE,
    SharedValues::GITHUB_API_STATUS_CODE,
    SharedValues::GITHUB_API_JSON
  ]

  UI.user_error!("Tag #{version} already exists in the GitHub repo") \
    if git_tag_exists(tag: version, remote: true, remote_name: GIT_REMOTE_NAME)
end

lane :build_xcframework do
  output = File.expand_path('./target/libwordpressFFI.xcframework.zip', PROJECT_ROOT)
  UI.user_error!("xcframework zip exists: #{output}") if File.exist?(output)

  UI.message("Switching to dir: #{PROJECT_ROOT}")
  checksum = Dir.chdir(PROJECT_ROOT) do
    sh 'make xcframework'
    source = File.expand_path('./target/libwordpressFFI.xcframework')
    zip(path: source, output_path: output)
    sh('swift', 'package', 'compute-checksum', output).chomp
  end

  lane_context[LANE_VALUE_XCFRAMEWORK] = output
  lane_context[LANE_VALUE_XCFRAMEWORK_CHECKSUM] = checksum

  [output, checksum]
end

lane :update_swift_package do
  version = lane_context[LANE_VALUE_VERSION] || UI.user_error!('Missing version lane context')

  UI.user_error!('Missing xcframework checksum lane context') unless lane_context.key?(LANE_VALUE_XCFRAMEWORK_CHECKSUM)
  checksum = lane_context[LANE_VALUE_XCFRAMEWORK_CHECKSUM]

  file_path = File.expand_path('./Package.swift', PROJECT_ROOT)
  lines = File.readlines(file_path).map do |line|
    if line.start_with?('let libwordpressFFIVersion: WordPressRSVersion =')
      "let libwordpressFFIVersion: WordPressRSVersion = .release(version: \"#{version}\", checksum: \"#{checksum}\")"
    else
      line
    end
  end
  File.open(file_path, 'w') { |file| file.puts lines }
end

lane :publish_github_release do
  version = lane_context[LANE_VALUE_VERSION] || UI.user_error!('Missing version lane context')
  github_token = lane_context[LANE_VALUE_GITHUB_TOKEN] || UI.user_error!('Missing github token lane context')

  UI.user_error!('Missing xcframework checksum lane context') unless lane_context.key?(LANE_VALUE_XCFRAMEWORK)
  xcframework = lane_context[LANE_VALUE_XCFRAMEWORK]
  UI.user_error!('Missing xcframework checksum lane context') unless File.exist?(xcframework)

  UI.user_error!('Missing xcframework checksum lane context') unless lane_context.key?(LANE_VALUE_XCFRAMEWORK_CHECKSUM)
  checksum = lane_context[LANE_VALUE_XCFRAMEWORK_CHECKSUM]
  checksum_file = "#{xcframework}.checksum.txt"
  File.write(checksum_file, checksum)

  # Create a new branch to commit the Package.swift changes.
  # Please note, the new commit is tagged and pushed to the remote. The new branch
  # is not pushed to the remote and can be discarded.
  sh "git checkout -b release/#{version}"
  git_commit(
    path: File.expand_path('./Package.swift', PROJECT_ROOT),
    message: "Update Package.swift to use version #{version}"
  )
  add_git_tag(tag: version)
  push_git_tags(tag: version, remote: GIT_REMOTE_NAME)
  set_github_release(
    api_token: github_token,
    repository_name: GITHUB_REPO,
    name: version,
    tag_name: version,
    description: "Release version #{version}",
    upload_assets: [xcframework, checksum_file]
  )
end

def remove_lane_context_values(names)
  names.each { |name| lane_context.delete(name) }
end
