[package]
name = "wp_serde_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true, features = [ "serde" ] }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
