[package]
name = "wp_com"
version = "0.1.0"
edition = "2021"

[features]
integration-tests = []

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_com"

[dependencies]
paste = { workspace = true }
serde = { workspace = true, features = [ "derive", "rc" ] }
serde_json = { workspace = true }
uniffi = { workspace = true }
url = { workspace = true }
wp_api = { path = "../wp_api" }
wp_contextual = { path = "../wp_contextual" }
wp_derive = { path = "../wp_derive" }
wp_derive_request_builder = { path = "../wp_derive_request_builder", features = [ "generate_request_builder" ] }
wp_localization = { path = "../wp_localization" }
wp_localization_macro = { path = "../wp_localization_macro" }
wp_serde_helper = { path = "../wp_serde_helper" }

[dev-dependencies]
rstest = { workspace = true }
