use std::sync::Arc;

pub use integration_test_credentials::TestCredentials;
pub use rstest::*;
pub use serial_test::{parallel, serial};
use url::Url;
use wp_api::{EmptyAppNotifier, prelude::*, reqwest_request_executor::ReqwestRequestExecutor};
pub use wp_api_integration_tests::backend::{Backend, RestoreServer};
use wp_mobile::service::WpSelfHostedService;
use wp_mobile_cache::WpApiCache;

pub fn test_site_url() -> ParsedUrl {
    let mut url: Url = TestCredentials::instance()
        .site_url
        .parse()
        .expect("Site url is generated by our tooling");
    url.path_segments_mut().unwrap().push("wp-json");
    url.into()
}

pub fn test_site_api_url_resolver() -> Arc<dyn ApiUrlResolver> {
    Arc::new(WpOrgSiteApiUrlResolver::new(test_site_url().into()))
}

pub fn api_client_delegate() -> WpApiClientDelegate {
    WpApiClientDelegate {
        auth_provider: Arc::new(WpAuthenticationProvider::static_with_username_and_password(
            TestCredentials::instance().admin_username.to_string(),
            TestCredentials::instance().admin_password.to_string(),
        )),
        request_executor: Arc::new(ReqwestRequestExecutor::default()),
        middleware_pipeline: Arc::new(WpApiMiddlewarePipeline::default()),
        app_notifier: Arc::new(EmptyAppNotifier),
    }
}

pub struct TestContext {
    pub api: WpApiClient,
    pub service: WpSelfHostedService,
    pub cache: Arc<WpApiCache>,
}

pub fn create_test_context() -> TestContext {
    let cache = Arc::new(WpApiCache::new(None).expect("Failed to create in-memory cache"));
    cache
        .perform_migrations()
        .expect("Migrations should succeed");

    let service = WpSelfHostedService::new(
        TestCredentials::instance().site_url.to_string(),
        test_site_url().to_string(),
        test_site_api_url_resolver(),
        api_client_delegate(),
        cache.clone(),
    )
    .expect("Failed to create WpSelfHostedService");

    let api = WpApiClient::new(test_site_api_url_resolver(), api_client_delegate());

    TestContext {
        api,
        service,
        cache,
    }
}

pub fn create_test_context_with_site(
    site_url: &str,
    username: &str,
    application_password: &str,
) -> TestContext {
    let mut api_root_url: Url = site_url.parse().expect("Invalid site URL");
    api_root_url.path_segments_mut().unwrap().push("wp-json");
    let api_root = api_root_url.to_string();

    let api_url_resolver: Arc<dyn ApiUrlResolver> = Arc::new(WpOrgSiteApiUrlResolver::new(
        ParsedUrl::from(api_root_url).into(),
    ));

    let delegate = WpApiClientDelegate {
        auth_provider: Arc::new(WpAuthenticationProvider::static_with_username_and_password(
            username.to_string(),
            application_password.to_string(),
        )),
        request_executor: Arc::new(ReqwestRequestExecutor::default()),
        middleware_pipeline: Arc::new(WpApiMiddlewarePipeline::default()),
        app_notifier: Arc::new(EmptyAppNotifier),
    };

    let cache = Arc::new(WpApiCache::new(None).expect("Failed to create in-memory cache"));
    cache
        .perform_migrations()
        .expect("Migrations should succeed");

    let service = WpSelfHostedService::new(
        site_url.to_string(),
        api_root,
        api_url_resolver.clone(),
        delegate.clone(),
        cache.clone(),
    )
    .expect("Failed to create WpSelfHostedService");

    let api = WpApiClient::new(api_url_resolver.clone(), delegate.clone());

    TestContext {
        api,
        service,
        cache,
    }
}
