use std::sync::Arc;

pub use integration_test_credentials::TestCredentials;
pub use rstest::*;
pub use serial_test::{parallel, serial};
use url::Url;
use wp_api::{EmptyAppNotifier, prelude::*, reqwest_request_executor::ReqwestRequestExecutor};
pub use wp_api_integration_tests::backend::{Backend, RestoreServer};
use wp_mobile::service::WpService;
use wp_mobile::service::sites::SiteInfo;
use wp_mobile_cache::WpApiCache;

pub fn test_site_url() -> ParsedUrl {
    let mut url: Url = TestCredentials::instance()
        .site_url
        .parse()
        .expect("Site url is generated by our tooling");
    url.path_segments_mut().unwrap().push("wp-json");
    url.into()
}

pub fn test_site_api_url_resolver() -> Arc<dyn ApiUrlResolver> {
    Arc::new(WpOrgSiteApiUrlResolver::new(test_site_url().into()))
}

pub fn api_client_delegate() -> WpApiClientDelegate {
    WpApiClientDelegate {
        auth_provider: Arc::new(WpAuthenticationProvider::static_with_username_and_password(
            TestCredentials::instance().admin_username.to_string(),
            TestCredentials::instance().admin_password.to_string(),
        )),
        request_executor: Arc::new(ReqwestRequestExecutor::default()),
        middleware_pipeline: Arc::new(WpApiMiddlewarePipeline::default()),
        app_notifier: Arc::new(EmptyAppNotifier),
    }
}

pub struct TestContext {
    pub api: WpApiClient,
    pub service: WpService,
    pub cache: Arc<WpApiCache>,
}

pub fn create_test_context() -> TestContext {
    let cache = Arc::new(WpApiCache::new(None).expect("Failed to create in-memory cache"));
    cache
        .perform_migrations()
        .expect("Migrations should succeed");

    let site_url = ParsedUrl::parse(TestCredentials::instance().site_url)
        .expect("Site url is generated by our tooling");
    let service = WpService::new(
        SiteInfo::SelfHosted {
            site_url: Arc::new(site_url),
            api_root: Arc::new(test_site_url()),
        },
        api_client_delegate(),
        cache.clone(),
    )
    .expect("Failed to create WpService");

    let api = WpApiClient::new(test_site_api_url_resolver(), api_client_delegate());

    TestContext {
        api,
        service,
        cache,
    }
}

/// Count rows in a table filtered by `db_site_id`.
pub fn count_rows_for_site(cache: &WpApiCache, table: &str, db_site_id: i64) -> usize {
    cache.execute(|conn| {
        let sql = format!("SELECT COUNT(*) FROM {} WHERE db_site_id = ?", table);
        let mut stmt = conn.prepare(&sql).expect("Failed to prepare count query");
        let count: i64 = stmt
            .query_row([db_site_id], |row| row.get(0))
            .expect("Failed to count rows");
        count as usize
    })
}

pub fn create_test_context_with_site(
    site_url: &str,
    username: &str,
    application_password: &str,
) -> TestContext {
    let mut api_root_url: Url = site_url.parse().expect("Invalid site URL");
    api_root_url.path_segments_mut().unwrap().push("wp-json");
    let api_root = api_root_url.to_string();

    let api_url_resolver: Arc<dyn ApiUrlResolver> = Arc::new(WpOrgSiteApiUrlResolver::new(
        ParsedUrl::from(api_root_url).into(),
    ));

    let delegate = WpApiClientDelegate {
        auth_provider: Arc::new(WpAuthenticationProvider::static_with_username_and_password(
            username.to_string(),
            application_password.to_string(),
        )),
        request_executor: Arc::new(ReqwestRequestExecutor::default()),
        middleware_pipeline: Arc::new(WpApiMiddlewarePipeline::default()),
        app_notifier: Arc::new(EmptyAppNotifier),
    };

    let cache = Arc::new(WpApiCache::new(None).expect("Failed to create in-memory cache"));
    cache
        .perform_migrations()
        .expect("Migrations should succeed");

    let parsed_site_url = ParsedUrl::parse(site_url).expect("Invalid site URL");
    let parsed_api_root = ParsedUrl::parse(&api_root).expect("Invalid API root URL");
    let service = WpService::new(
        SiteInfo::SelfHosted {
            site_url: Arc::new(parsed_site_url),
            api_root: Arc::new(parsed_api_root),
        },
        delegate.clone(),
        cache.clone(),
    )
    .expect("Failed to create WpService");

    let api = WpApiClient::new(api_url_resolver.clone(), delegate.clone());

    TestContext {
        api,
        service,
        cache,
    }
}
