[package]
name = "wp_mobile_cache"
version = "0.1.0"
edition = "2024"

[features]
default = ["rusqlite/bundled"]
test-helpers = ["dep:chrono", "dep:integration_test_credentials", "dep:rstest"]

[dependencies]
log = { workspace = true }
rusqlite = { workspace = true, features = ["hooks"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uniffi = { workspace = true }
wp_api = { path = "../wp_api" }

[dev-dependencies]
chrono = { workspace = true }
integration_test_credentials = { path = "../integration_test_credentials" }
rstest = { workspace = true }

# Optional dependencies (enabled via test-helpers feature)
[dependencies.chrono]
workspace = true
optional = true

[dependencies.integration_test_credentials]
path = "../integration_test_credentials"
optional = true

[dependencies.rstest]
optional = true
workspace = true
