// Expose necessary Rust APIs as public API to the Swift package's consumers.
//
// We could export all of them using `@_exported import`, but that probably puts
// us in a position where we need to make major releases due to Rust code changes.
// swiftlint:disable line_length

import WordPressAPIInternal

public typealias WpApiError = WordPressAPIInternal.WpApiError
public typealias RequestExecutionError = WordPressAPIInternal.RequestExecutionError
public typealias InvalidSslErrorReason = WordPressAPIInternal.InvalidSslErrorReason
public typealias ParsedUrl = WordPressAPIInternal.ParsedUrl
public typealias QueryPair = WordPressAPIInternal.QueryPair
public typealias ResolvedUrl = WordPressAPIInternal.ResolvedUrl
public typealias WpUuid = WordPressAPIInternal.WpUuid
public typealias WpNetworkRequest = WordPressAPIInternal.WpNetworkRequest
public typealias WpNetworkResponse = WordPressAPIInternal.WpNetworkResponse
public typealias WpNetworkHeaderMap = WordPressAPIInternal.WpNetworkHeaderMap
public typealias WpResponseString = WordPressAPIInternal.WpResponseString
public typealias Middleware = WordPressAPIInternal.WpApiMiddleware
public typealias MiddlewarePipeline = WordPressAPIInternal.WpApiMiddlewarePipeline
public typealias MiddlewarePipelineBuilder = WordPressAPIInternal.WpApiMiddlewarePipelineBuilder
public typealias ApiDiscoveryAuthenticationMiddleware = WordPressAPIInternal.ApiDiscoveryAuthenticationMiddleware
public typealias RetryAfterMiddleware = WordPressAPIInternal.RetryAfterMiddleware
public typealias WpApiClientDelegate = WordPressAPIInternal.WpApiClientDelegate
public typealias WpAppNotifier = WordPressAPIInternal.WpAppNotifier
public typealias UserAvatarSize = WordPressAPIInternal.UserAvatarSize
public typealias WpApiDetails = WordPressAPIInternal.WpApiDetails
public typealias ApiUrlResolver = WordPressAPIInternal.ApiUrlResolver
public typealias WpComDotOrgApiUrlResolver = WordPressAPIInternal.WpComDotOrgApiUrlResolver
public typealias WpOrgSiteApiUrlResolver = WordPressAPIInternal.WpOrgSiteApiUrlResolver
public typealias WpApiParamOrder = WordPressAPIInternal.WpApiParamOrder
public typealias UserCapability = WordPressAPIInternal.UserCapability
public typealias UserRole = WordPressAPIInternal.UserRole

// MARK: - Service Layer
public typealias WpService = WordPressAPIInternal.WpService
public typealias SiteInfo = WordPressAPIInternal.SiteInfo
public typealias AnyPostFilter = WordPressAPIInternal.AnyPostFilter
public typealias WpApiCache = WordPressAPIInternal.WpApiCache

// MARK: - Login

public typealias WpApiApplicationPasswordDetails = WordPressAPIInternal.WpApiApplicationPasswordDetails
public typealias WpAuthentication = WordPressAPIInternal.WpAuthentication
public typealias SSLCertificateInfo = WordPressAPIInternal.SslCertificateInfo
public typealias AutoDiscoveryAttemptSuccess = WordPressAPIInternal.AutoDiscoveryAttemptSuccess
public typealias DiscoveredAuthenticationMechanism = WordPressAPIInternal.DiscoveredAuthenticationMechanism
public typealias WpDynamicAuthenticationProvider = WordPressAPIInternal.WpDynamicAuthenticationProvider

// MARK: - Errors
public typealias AutoDiscoveryAttemptFailure = WordPressAPIInternal.AutoDiscoveryAttemptFailure
public typealias FindApiRootFailure = WordPressAPIInternal.FindApiRootFailure
public typealias FetchAndParseApiRootFailure = WordPressAPIInternal.FetchAndParseApiRootFailure
public typealias ApplicationPasswordsNotSupportedReason = WordPressAPIInternal.ApplicationPasswordsNotSupportedReason
public typealias RequestExecutionErrorReason = WordPressAPIInternal.RequestExecutionErrorReason

// MARK: - Users

public typealias UserId = WordPressAPIInternal.UserId
public typealias SparseUser = WordPressAPIInternal.SparseUser
public typealias UserWithViewContext = WordPressAPIInternal.UserWithViewContext
public typealias UserWithEditContext = WordPressAPIInternal.UserWithEditContext
public typealias UserWithEmbedContext = WordPressAPIInternal.UserWithEmbedContext
public typealias UserListParams = WordPressAPIInternal.UserListParams
public typealias UserUpdateParams = WordPressAPIInternal.UserUpdateParams
public typealias UserCreateParams = WordPressAPIInternal.UserCreateParams
public typealias UserDeleteParams = WordPressAPIInternal.UserDeleteParams
public typealias UserDeleteResponse = WordPressAPIInternal.UserDeleteResponse
public typealias UsersRequestExecutor = WordPressAPIInternal.UsersRequestExecutor

public typealias UsersRequestListWithEditContextResponse = WordPressAPIInternal.UsersRequestListWithEditContextResponse
public typealias UsersRequestListWithViewContextResponse = WordPressAPIInternal.UsersRequestListWithViewContextResponse
public typealias UsersRequestListWithEmbedContextResponse = WordPressAPIInternal
    .UsersRequestListWithEmbedContextResponse

// MARK: - Plugins

public typealias SparsePlugin = WordPressAPIInternal.SparsePlugin
public typealias PluginWithViewContext = WordPressAPIInternal.PluginWithViewContext
public typealias PluginWithEditContext = WordPressAPIInternal.PluginWithEditContext
public typealias PluginWithEmbedContext = WordPressAPIInternal.PluginWithEmbedContext
public typealias PluginSlug = WordPressAPIInternal.PluginSlug
public typealias PluginListParams = WordPressAPIInternal.PluginListParams
public typealias PluginUpdateParams = WordPressAPIInternal.PluginUpdateParams
public typealias PluginCreateParams = WordPressAPIInternal.PluginCreateParams
public typealias PluginDeleteResponse = WordPressAPIInternal.PluginDeleteResponse
public typealias PluginsRequestExecutor = WordPressAPIInternal.PluginsRequestExecutor
public typealias PluginStatus = WordPressAPIInternal.PluginStatus

public typealias PluginWpOrgDirectorySlug = WordPressAPIInternal.PluginWpOrgDirectorySlug
public typealias PluginWpOrgDirectoryCategory = WordPressAPIInternal.WordPressOrgApiPluginDirectoryCategory
public typealias PluginInformation = WordPressAPIInternal.PluginInformation
public typealias UpdateCheckPluginInfo = WordPressAPIInternal.UpdateCheckPluginInfo

// MARK: – Application Passwords

public typealias SparseApplicationPassword = WordPressAPIInternal.SparseApplicationPassword
public typealias ApplicationPasswordWithEditContext = WordPressAPIInternal.ApplicationPasswordWithEditContext
public typealias ApplicationPasswordWithViewContext = WordPressAPIInternal.ApplicationPasswordWithViewContext
public typealias ApplicationPasswordWithEmbedContext = WordPressAPIInternal.ApplicationPasswordWithEmbedContext
public typealias ApplicationPasswordsRequestExecutor = WordPressAPIInternal.ApplicationPasswordsRequestExecutor

// MARK: - Site Health Checks
public typealias SiteHealthTest = WordPressAPIInternal.WpSiteHealthTest
public typealias SiteHealthDirectorySizes = WordPressAPIInternal.WpSiteHealthDirectorySizes

// MARK: – Post Types
public typealias PostType = WordPressAPIInternal.PostType
public typealias SparsePostType = WordPressAPIInternal.SparsePostTypeDetails
public typealias PostTypeWithEditContext = WordPressAPIInternal.PostTypeDetailsWithEditContext
public typealias PostTypeWithViewContext = WordPressAPIInternal.PostTypeDetailsWithViewContext
public typealias PostTypeWithEmbedContext = WordPressAPIInternal.PostTypeDetailsWithEmbedContext
public typealias PostTypeDetailsWithEditContext = WordPressAPIInternal.PostTypeDetailsWithEditContext
public typealias PostTypeDetailsWithViewContext = WordPressAPIInternal.PostTypeDetailsWithViewContext
public typealias PostTypeDetailsWithEmbedContext = WordPressAPIInternal.PostTypeDetailsWithEmbedContext
public typealias PostTypesRequestExecutor = WordPressAPIInternal.PostTypesRequestExecutor

// MARK: – Post Statuses
public typealias PostStatusSlug = WordPressAPIInternal.PostStatusSlug
public typealias SparsePostStatus = WordPressAPIInternal.SparsePostStatus
public typealias PostStatusWithEditContext = WordPressAPIInternal.PostStatusWithEditContext
public typealias PostStatusWithViewContext = WordPressAPIInternal.PostStatusWithViewContext
public typealias PostStatusWithEmbedContext = WordPressAPIInternal.PostStatusWithEmbedContext
public typealias PostStatusesRequestExecutor = WordPressAPIInternal.PostStatusesRequestExecutor

public typealias PostStatusesRequestListWithEditContextResponse = WordPressAPIInternal
    .PostStatusesRequestListWithEditContextResponse
public typealias PostStatusesRequestListWithViewContextResponse = WordPressAPIInternal
    .PostStatusesRequestListWithViewContextResponse
public typealias PostStatusesRequestListWithEmbedContextResponse = WordPressAPIInternal
    .PostStatusesRequestListWithEmbedContextResponse

// MARK: - Posts
public typealias SparseAnyPost = WordPressAPIInternal.SparseAnyPost
public typealias AnyPostWithEditContext = WordPressAPIInternal.AnyPostWithEditContext
public typealias AnyPostWithViewContext = WordPressAPIInternal.AnyPostWithViewContext
public typealias AnyPostWithEmbedContext = WordPressAPIInternal.AnyPostWithEmbedContext
public typealias PostListParams = WordPressAPIInternal.PostListParams
public typealias PostUpdateParams = WordPressAPIInternal.PostUpdateParams
public typealias PostsRequestExecutor = WordPressAPIInternal.PostsRequestExecutor
public typealias PostEndpointType = WordPressAPIInternal.PostEndpointType

public typealias PostsRequestListWithEditContextResponse = WordPressAPIInternal.PostsRequestListWithEditContextResponse
public typealias PostsRequestListWithViewContextResponse = WordPressAPIInternal.PostsRequestListWithViewContextResponse
public typealias PostsRequestListWithEmbedContextResponse = WordPressAPIInternal
    .PostsRequestListWithEmbedContextResponse

extension AnyPostWithEditContext: Identifiable {}

// MARK: – Revisions
public typealias SparseAnyRevision = WordPressAPIInternal.SparseAnyPostRevision
public typealias RevisionWithEditContext = WordPressAPIInternal.AnyPostRevisionWithEditContext
public typealias RevisionWithViewContext = WordPressAPIInternal.AnyPostRevisionWithViewContext
public typealias RevisionWithEmbedContext = WordPressAPIInternal.AnyPostRevisionWithEmbedContext
public typealias RevisionListParams = WordPressAPIInternal.AnyPostRevisionListParams
public typealias RevisionsRequestExecutor = WordPressAPIInternal.PostRevisionsRequestExecutor

public typealias RevisionsRequestListWithEditContextResponse = WordPressAPIInternal
    .PostRevisionsRequestListWithEditContextResponse
public typealias RevisionsRequestListWithViewContextResponse = WordPressAPIInternal
    .PostRevisionsRequestListWithViewContextResponse
public typealias RevisionsRequestListWithEmbedContextResponse = WordPressAPIInternal
    .PostRevisionsRequestListWithEmbedContextResponse

// MARK: - Media
public typealias SparseMedia = WordPressAPIInternal.SparseMedia
public typealias MediaWithEditContext = WordPressAPIInternal.MediaWithEditContext
public typealias MediaWithViewContext = WordPressAPIInternal.MediaWithViewContext
public typealias MediaWithEmbedContext = WordPressAPIInternal.MediaWithEmbedContext
public typealias MediaCreateParams = WordPressAPIInternal.MediaCreateParams
public typealias MediaUpdateParams = WordPressAPIInternal.MediaUpdateParams
public typealias MediaListParams = WordPressAPIInternal.MediaListParams
public typealias MediaRequestExecutor = WordPressAPIInternal.MediaRequestExecutor

public typealias MediaRequestListWithEditContextResponse = WordPressAPIInternal.MediaRequestListWithEditContextResponse
public typealias MediaRequestListWithViewContextResponse = WordPressAPIInternal.MediaRequestListWithViewContextResponse
public typealias MediaRequestListWithEmbedContextResponse = WordPressAPIInternal
    .MediaRequestListWithEmbedContextResponse

// MARK: - Comments
public typealias SparseComment = WordPressAPIInternal.SparseComment
public typealias CommentWithEditContext = WordPressAPIInternal.CommentWithEditContext
public typealias CommentWithViewContext = WordPressAPIInternal.CommentWithViewContext
public typealias CommentWithEmbedContext = WordPressAPIInternal.CommentWithEmbedContext
public typealias CommentListParams = WordPressAPIInternal.CommentListParams
public typealias CommentCreateParams = WordPressAPIInternal.CommentCreateParams
public typealias CommentUpdateParams = WordPressAPIInternal.CommentUpdateParams
public typealias CommentDeleteParams = WordPressAPIInternal.CommentDeleteParams
public typealias CommentStatus = WordPressAPIInternal.CommentStatus
public typealias CommentType = WordPressAPIInternal.CommentType
public typealias CommentsRequestExecutor = WordPressAPIInternal.CommentsRequestExecutor

public typealias CommentsRequestListWithEditContextResponse = WordPressAPIInternal
    .CommentsRequestListWithEditContextResponse
public typealias CommentsRequestListWithViewContextResponse = WordPressAPIInternal
    .CommentsRequestListWithViewContextResponse
public typealias CommentsRequestListWithEmbedContextResponse = WordPressAPIInternal
    .CommentsRequestListWithEmbedContextResponse

// MARK: - Terms
public typealias TermId = WordPressAPIInternal.TermId
public typealias SparseAnyTerm = WordPressAPIInternal.SparseAnyTerm
public typealias AnyTermWithEditContext = WordPressAPIInternal.AnyTermWithEditContext
public typealias AnyTermWithViewContext = WordPressAPIInternal.AnyTermWithViewContext
public typealias AnyTermWithEmbedContext = WordPressAPIInternal.AnyTermWithEmbedContext
public typealias TermCreateParams = WordPressAPIInternal.TermCreateParams
public typealias TermUpdateParams = WordPressAPIInternal.TermUpdateParams
public typealias TermListParams = WordPressAPIInternal.TermListParams
public typealias WpApiParamTermsOrderBy = WordPressAPIInternal.WpApiParamTermsOrderBy
public typealias TermEndpointType = WordPressAPIInternal.TermEndpointType
public typealias TermsRequestExecutor = WordPressAPIInternal.TermsRequestExecutor
public typealias TermsRequestListWithEditContextResponse = WordPressAPIInternal.TermsRequestListWithEditContextResponse
public typealias TermsRequestListWithViewContextResponse = WordPressAPIInternal.TermsRequestListWithViewContextResponse
public typealias TermsRequestListWithEmbedContextResponse = WordPressAPIInternal
    .TermsRequestListWithEmbedContextResponse

// MARK: - Taxonomies
public typealias TaxonomyListParams = WordPressAPIInternal.TaxonomyListParams

// MARK: Navigation
public typealias NavigationStatus = WordPressAPIInternal.NavigationStatus
public typealias NavigationListParams = WordPressAPIInternal.NavigationListParams
public typealias NavigationCreateParams = WordPressAPIInternal.NavigationCreateParams
public typealias NavigationUpdateParams = WordPressAPIInternal.NavigationUpdateParams
public typealias NavigationRetrieveParams = WordPressAPIInternal.NavigationRetrieveParams
public typealias NavigationRequestExecutor = WordPressAPIInternal.NavigationsRequestExecutor
public typealias NavigationWithEditContext = WordPressAPIInternal.NavigationWithEditContext
public typealias NavigationWithViewContext = WordPressAPIInternal.NavigationWithViewContext
public typealias NavigationWithEmbedContext = WordPressAPIInternal.NavigationWithEmbedContext

public typealias NavigationRevisionListParams = WordPressAPIInternal.NavigationRevisionListParams
public typealias NavigationRevisionWithEditContext = WordPressAPIInternal.NavigationRevisionWithEditContext
public typealias NavigationRevisionWithViewContext = WordPressAPIInternal.NavigationRevisionWithViewContext
public typealias NavigationRevisionWithEmbedContext = WordPressAPIInternal.NavigationRevisionWithEmbedContext

// MARK: - Menus
public typealias SparseNavMenu = WordPressAPIInternal.SparseNavMenu
public typealias NavMenuListParams = WordPressAPIInternal.NavMenuListParams
public typealias NavMenuCreateParams = WordPressAPIInternal.NavMenuCreateParams
public typealias NavMenuUpdateParams = WordPressAPIInternal.NavMenuUpdateParams
public typealias NavMenuWithEditContext = WordPressAPIInternal.NavMenuWithEditContext
public typealias NavMenuWithViewContext = WordPressAPIInternal.NavMenuWithViewContext
public typealias NavMenuWithEmbedContext = WordPressAPIInternal.NavMenuWithEmbedContext

// MARK: - Menu Items
public typealias NavMenuItemListParams = WordPressAPIInternal.NavMenuItemListParams
public typealias NavMenuItemCreateParams = WordPressAPIInternal.NavMenuItemCreateParams
public typealias NavMenuItemUpdateParams = WordPressAPIInternal.NavMenuItemUpdateParams
public typealias NavMenuItemWithEditContext = WordPressAPIInternal.NavMenuItemWithEditContext
public typealias NavMenuItemWithViewContext = WordPressAPIInternal.NavMenuItemWithViewContext
public typealias NavMenuItemWithEmbedContext = WordPressAPIInternal.NavMenuItemWithEmbedContext
public typealias NavMenuItemsRequestExecutor = WordPressAPIInternal.NavMenuItemsRequestExecutor
public typealias NavMenuItemsRequestListWithEditContextResponse = WordPressAPIInternal
    .NavMenuItemsRequestListWithEditContextResponse
public typealias NavMenuItemsRequestListWithViewContextResponse = WordPressAPIInternal
    .NavMenuItemsRequestListWithViewContextResponse
public typealias NavMenuItemsRequestListWithEmbedContextResponse = WordPressAPIInternal
    .NavMenuItemsRequestListWithEmbedContextResponse

// MARK: Menu Item Autosaves
public typealias NavMenuItemRevisionCreateParams = WordPressAPIInternal.NavMenuItemRevisionCreateParams
public typealias NavMenuItemRevisionWithEditContext = WordPressAPIInternal.NavMenuItemRevisionWithEditContext
public typealias NavMenuItemRevisionWithViewContext = WordPressAPIInternal.NavMenuItemRevisionWithViewContext
public typealias NavMenuItemRevisionWithEmbedContext = WordPressAPIInternal.NavMenuItemRevisionWithEmbedContext

// MARK: Menu Locations
public typealias MenuLocationWithEditContext = WordPressAPIInternal.MenuLocationWithEditContext
public typealias MenuLocationWithViewContext = WordPressAPIInternal.MenuLocationWithViewContext
public typealias MenuLocationWithEmbedContext = WordPressAPIInternal.MenuLocationWithEmbedContext

// MARK: – Site Settings
public typealias SparseSiteSettings = WordPressAPIInternal.SparseSiteSettings
public typealias SiteSettingsWithEditContext = WordPressAPIInternal.SiteSettingsWithEditContext
public typealias SiteSettingsWithViewContext = WordPressAPIInternal.SiteSettingsWithViewContext
public typealias SiteSettingsWithEmbedContext = WordPressAPIInternal.SiteSettingsWithEmbedContext

// MARK: – Site Settings
public typealias SiteSettingsRequestExecutor = WordPressAPIInternal.SiteSettingsRequestExecutor

// MARK: – Site Health Tests
public typealias WpSiteHealthTestsRequestExecutor = WordPressAPIInternal.WpSiteHealthTestsRequestExecutor
// swiftlint:enable line_length

// MARK: - Themes
public typealias ThemeListParams = WordPressAPIInternal.ThemeListParams

// MARK: - Block Editor
public typealias WpBlockEditorSettingsParams = WordPressAPIInternal.WpBlockEditorSettingsParams

// MARK: - WordPress.org
public typealias WordPressOrgApiClient = WordPressAPIInternal.WordPressOrgApiClient

// MARK: - WordPress.com

// MARK: OAuth2
public typealias TokenValidationParameters = WordPressAPIInternal.TokenValidationParameters
public typealias TokenRequestParameters = WordPressAPIInternal.TokenRequestParameters
public typealias WpComOauthScope = WordPressAPIInternal.WpComOauthScope
public typealias OAuth2Configuration = WordPressAPIInternal.OAuth2Configuration
public typealias OAuth2ConfigurationStore = WordPressAPIInternal.OAuth2ConfigurationStore
public typealias WpComSiteIdentifier = WordPressAPIInternal.WpComSiteIdentifier

// MARK: Languages
public typealias WPComLanguage = WordPressAPIInternal.WpComLanguage
public typealias LanguagesGetParams = WordPressAPIInternal.LanguagesGetParams

// MARK: Subscribers
public typealias SubscribersListParams = WordPressAPIInternal.SubscribersListParams
public typealias SubscriberImportJobsListParams = WordPressAPIInternal.SubscriberImportJobsListParams
public typealias AddSubscribersParams = WordPressAPIInternal.AddSubscribersParams

// MARK: Support Bots
public typealias ListBotConversationParams = WordPressAPIInternal.ListBotConversationsParams
public typealias CreateBotConversationParams = WordPressAPIInternal.CreateBotConversationParams
public typealias AddMessageToBotConversationParams = WordPressAPIInternal.AddMessageToBotConversationParams
public typealias GetBotConversationParams = WordPressAPIInternal.GetBotConversationParams
public typealias CreateBotConversationFeedbackParams = WordPressAPIInternal.CreateBotConversationFeedbackParams

// MARK: Support Tickets
public typealias CreateSupportTicketParams = WordPressAPIInternal.CreateSupportTicketParams
public typealias AddMessageToSupportConversationParams = WordPressAPIInternal.AddMessageToSupportConversationParams

// MARK: - Jetpack
public typealias JetpackConnectionClient = WordPressAPIInternal.JetpackConnectionClient

// MARK: - Persistence
public typealias Account = WordPressAPIInternal.Account
public typealias AccountId = UInt64
public typealias AccountRepository = WordPressAPIInternal.AccountRepository
public typealias AccountRepositoryError = WordPressAPIInternal.AccountRepositoryError
#if os(Linux)
public typealias AesGcmPasswordTransformer = WordPressAPIInternal.AesGcmPasswordTransformer
#endif
public typealias EncryptedPassword = WordPressAPIInternal.EncryptedPassword
public typealias DecryptedPassword = WordPressAPIInternal.DecryptedPassword
public typealias PasswordTransformer = WordPressAPIInternal.PasswordTransformer
public typealias PasswordTransformerError = WordPressAPIInternal.PasswordTransformerError

// MARK: - Publicize & Keyring

public typealias PublicizeConnectionResponse = WordPressAPIInternal.PublicizeConnectionResponse
public typealias PublicizeServiceResponse = WordPressAPIInternal.PublicizeServiceResponse
public typealias PublicizeServiceSupports = WordPressAPIInternal.PublicizeServiceSupports
public typealias KeyringConnectionResponse = WordPressAPIInternal.KeyringConnectionResponse
public typealias KeyringExternalUser = WordPressAPIInternal.KeyringExternalUser
public typealias PublicizeConnectionId = WordPressAPIInternal.PublicizeConnectionId
public typealias CreatePublicizeConnectionParams = WordPressAPIInternal.CreatePublicizeConnectionParams
public typealias UpdatePublicizeConnectionParams = WordPressAPIInternal.UpdatePublicizeConnectionParams
public typealias PublicizeRequestListConnectionsResponse = WordPressAPIInternal.PublicizeRequestListConnectionsResponse
public typealias PublicizeRequestListServicesResponse = WordPressAPIInternal.PublicizeRequestListServicesResponse
public typealias PublicizeRequestCreateConnectionResponse = WordPressAPIInternal
    .PublicizeRequestCreateConnectionResponse
public typealias PublicizeRequestUpdateConnectionResponse = WordPressAPIInternal
    .PublicizeRequestUpdateConnectionResponse
public typealias PublicizeRequestDeleteConnectionResponse = WordPressAPIInternal
    .PublicizeRequestDeleteConnectionResponse
public typealias MeConnectionsRequestListResponse = WordPressAPIInternal.MeConnectionsRequestListResponse
public typealias MeConnectionsResponse = WordPressAPIInternal.MeConnectionsResponse

// MARK: - JSON helpers

public typealias WpAdditionalFields = WordPressAPIInternal.WpAdditionalFields
public typealias AdditionalFieldsParseError = WordPressAPIInternal.AdditionalFieldsParseError
public typealias JsonValue = WordPressAPIInternal.JsonValue
