// Expose necessary Rust APIs as public API to the Swift package's consumers.
//
// We could export all of them using `@_exported import`, but that probably puts
// us in a position where we need to make major releases due to Rust code changes.
// swiftlint:disable line_length

import WordPressAPIInternal

public typealias WpApiError = WordPressAPIInternal.WpApiError
public typealias RequestExecutionError = WordPressAPIInternal.RequestExecutionError
public typealias InvalidSslErrorReason = WordPressAPIInternal.InvalidSslErrorReason
public typealias ParsedUrl = WordPressAPIInternal.ParsedUrl
public typealias WpUuid = WordPressAPIInternal.WpUuid
public typealias WpNetworkRequest = WordPressAPIInternal.WpNetworkRequest
public typealias WpNetworkResponse = WordPressAPIInternal.WpNetworkResponse
public typealias WpNetworkHeaderMap = WordPressAPIInternal.WpNetworkHeaderMap
public typealias WpResponseString = WordPressAPIInternal.WpResponseString
public typealias Middleware = WordPressAPIInternal.WpApiMiddleware
public typealias MiddlewarePipeline = WordPressAPIInternal.WpApiMiddlewarePipeline
public typealias MiddlewarePipelineBuilder = WordPressAPIInternal.WpApiMiddlewarePipelineBuilder
public typealias ApiDiscoveryAuthenticationMiddleware = WordPressAPIInternal.ApiDiscoveryAuthenticationMiddleware
public typealias RetryAfterMiddleware = WordPressAPIInternal.RetryAfterMiddleware
public typealias WpApiClientDelegate = WordPressAPIInternal.WpApiClientDelegate
public typealias WpAppNotifier = WordPressAPIInternal.WpAppNotifier
public typealias UserAvatarSize = WordPressAPIInternal.UserAvatarSize
public typealias WpApiDetails = WordPressAPIInternal.WpApiDetails
public typealias ApiUrlResolver = WordPressAPIInternal.ApiUrlResolver
public typealias WpComDotOrgApiUrlResolver = WordPressAPIInternal.WpComDotOrgApiUrlResolver
public typealias WpOrgSiteApiUrlResolver = WordPressAPIInternal.WpOrgSiteApiUrlResolver
public typealias WpApiParamOrder = WordPressAPIInternal.WpApiParamOrder
public typealias UserCapability = WordPressAPIInternal.UserCapability
public typealias UserRole = WordPressAPIInternal.UserRole

// MARK: - Login

public typealias WpApiApplicationPasswordDetails = WordPressAPIInternal.WpApiApplicationPasswordDetails
public typealias WpAuthentication = WordPressAPIInternal.WpAuthentication
public typealias SSLCertificateInfo = WordPressAPIInternal.SslCertificateInfo
public typealias AutoDiscoveryAttemptSuccess = WordPressAPIInternal.AutoDiscoveryAttemptSuccess
public typealias WpDynamicAuthenticationProvider = WordPressAPIInternal.WpDynamicAuthenticationProvider

// MARK: - Errors
public typealias AutoDiscoveryAttemptFailure = WordPressAPIInternal.AutoDiscoveryAttemptFailure
public typealias FindApiRootFailure = WordPressAPIInternal.FindApiRootFailure
public typealias FetchAndParseApiRootFailure = WordPressAPIInternal.FetchAndParseApiRootFailure
public typealias ApplicationPasswordsNotSupportedReason = WordPressAPIInternal.ApplicationPasswordsNotSupportedReason
public typealias RequestExecutionErrorReason = WordPressAPIInternal.RequestExecutionErrorReason

// MARK: - Users

public typealias UserId = WordPressAPIInternal.UserId
public typealias SparseUser = WordPressAPIInternal.SparseUser
public typealias UserWithViewContext = WordPressAPIInternal.UserWithViewContext
public typealias UserWithEditContext = WordPressAPIInternal.UserWithEditContext
public typealias UserWithEmbedContext = WordPressAPIInternal.UserWithEmbedContext
public typealias UserListParams = WordPressAPIInternal.UserListParams
public typealias UserUpdateParams = WordPressAPIInternal.UserUpdateParams
public typealias UserCreateParams = WordPressAPIInternal.UserCreateParams
public typealias UserDeleteParams = WordPressAPIInternal.UserDeleteParams
public typealias UserDeleteResponse = WordPressAPIInternal.UserDeleteResponse
public typealias UsersRequestExecutor = WordPressAPIInternal.UsersRequestExecutor

public typealias UsersRequestListWithEditContextResponse = WordPressAPIInternal.UsersRequestListWithEditContextResponse
public typealias UsersRequestListWithViewContextResponse = WordPressAPIInternal.UsersRequestListWithViewContextResponse
public typealias UsersRequestListWithEmbedContextResponse = WordPressAPIInternal.UsersRequestListWithEmbedContextResponse

// MARK: - Plugins

public typealias SparsePlugin = WordPressAPIInternal.SparsePlugin
public typealias PluginWithViewContext = WordPressAPIInternal.PluginWithViewContext
public typealias PluginWithEditContext = WordPressAPIInternal.PluginWithEditContext
public typealias PluginWithEmbedContext = WordPressAPIInternal.PluginWithEmbedContext
public typealias PluginSlug = WordPressAPIInternal.PluginSlug
public typealias PluginListParams = WordPressAPIInternal.PluginListParams
public typealias PluginUpdateParams = WordPressAPIInternal.PluginUpdateParams
public typealias PluginCreateParams = WordPressAPIInternal.PluginCreateParams
public typealias PluginDeleteResponse = WordPressAPIInternal.PluginDeleteResponse
public typealias PluginsRequestExecutor = WordPressAPIInternal.PluginsRequestExecutor
public typealias PluginStatus = WordPressAPIInternal.PluginStatus

public typealias PluginWpOrgDirectorySlug = WordPressAPIInternal.PluginWpOrgDirectorySlug
public typealias PluginWpOrgDirectoryCategory = WordPressAPIInternal.WordPressOrgApiPluginDirectoryCategory
public typealias PluginInformation = WordPressAPIInternal.PluginInformation
public typealias UpdateCheckPluginInfo = WordPressAPIInternal.UpdateCheckPluginInfo

// MARK: – Application Passwords

public typealias SparseApplicationPassword = WordPressAPIInternal.SparseApplicationPassword
public typealias ApplicationPasswordWithEditContext = WordPressAPIInternal.ApplicationPasswordWithEditContext
public typealias ApplicationPasswordWithViewContext = WordPressAPIInternal.ApplicationPasswordWithViewContext
public typealias ApplicationPasswordWithEmbedContext = WordPressAPIInternal.ApplicationPasswordWithEmbedContext
public typealias ApplicationPasswordsRequestExecutor = WordPressAPIInternal.ApplicationPasswordsRequestExecutor

// MARK: - Site Health Checks
public typealias SiteHealthTest = WordPressAPIInternal.WpSiteHealthTest
public typealias SiteHealthDirectorySizes = WordPressAPIInternal.WpSiteHealthDirectorySizes

// MARK: – Post Types
public typealias PostType = WordPressAPIInternal.PostType
public typealias SparsePostType = WordPressAPIInternal.SparsePostTypeDetails
public typealias PostTypeWithEditContext = WordPressAPIInternal.PostTypeDetailsWithEditContext
public typealias PostTypeWithViewContext = WordPressAPIInternal.PostTypeDetailsWithViewContext
public typealias PostTypeWithEmbedContext = WordPressAPIInternal.PostTypeDetailsWithEmbedContext
public typealias PostTypeDetailsWithEditContext = WordPressAPIInternal.PostTypeDetailsWithEditContext
public typealias PostTypeDetailsWithViewContext = WordPressAPIInternal.PostTypeDetailsWithViewContext
public typealias PostTypeDetailsWithEmbedContext = WordPressAPIInternal.PostTypeDetailsWithEmbedContext
public typealias PostTypesRequestExecutor = WordPressAPIInternal.PostTypesRequestExecutor

// MARK: - Posts
public typealias SparsePost = WordPressAPIInternal.SparsePost
public typealias PostWithEditContext = WordPressAPIInternal.PostWithEditContext
public typealias PostWithViewContext = WordPressAPIInternal.PostWithViewContext
public typealias PostWithEmbedContext = WordPressAPIInternal.PostWithEmbedContext
public typealias PostListParams = WordPressAPIInternal.PostListParams
public typealias PostsRequestExecutor = WordPressAPIInternal.PostsRequestExecutor

public typealias PostsRequestListWithEditContextResponse = WordPressAPIInternal.PostsRequestListWithEditContextResponse
public typealias PostsRequestListWithViewContextResponse = WordPressAPIInternal.PostsRequestListWithViewContextResponse
public typealias PostsRequestListWithEmbedContextResponse = WordPressAPIInternal.PostsRequestListWithEmbedContextResponse

// MARK: - Pages
public typealias SparsePage = WordPressAPIInternal.SparsePage
public typealias PageWithEditContext = WordPressAPIInternal.PageWithEditContext
public typealias PageWithViewContext = WordPressAPIInternal.PageWithViewContext
public typealias PageWithEmbedContext = WordPressAPIInternal.PageWithEmbedContext
public typealias PageListParams = WordPressAPIInternal.PageListParams
public typealias PagesRequestExecutor = WordPressAPIInternal.PagesRequestExecutor

public typealias PagesRequestListWithEditContextResponse = WordPressAPIInternal.PagesRequestListWithEditContextResponse
public typealias PagesRequestListWithViewContextResponse = WordPressAPIInternal.PagesRequestListWithViewContextResponse
public typealias PagesRequestListWithEmbedContextResponse = WordPressAPIInternal.PagesRequestListWithEmbedContextResponse

// MARK: - Media
public typealias SparseMedia = WordPressAPIInternal.SparseMedia
public typealias MediaUploadRequest = WordPressAPIInternal.MediaUploadRequest
public typealias MediaWithEditContext = WordPressAPIInternal.MediaWithEditContext
public typealias MediaWithViewContext = WordPressAPIInternal.MediaWithViewContext
public typealias MediaWithEmbedContext = WordPressAPIInternal.MediaWithEmbedContext
public typealias MediaCreateParams = WordPressAPIInternal.MediaCreateParams
public typealias MediaUpdateParams = WordPressAPIInternal.MediaUpdateParams
public typealias MediaListParams = WordPressAPIInternal.MediaListParams
public typealias MediaRequestExecutor = WordPressAPIInternal.MediaRequestExecutor

public typealias MediaRequestListWithEditContextResponse = WordPressAPIInternal.MediaRequestListWithEditContextResponse
public typealias MediaRequestListWithViewContextResponse = WordPressAPIInternal.MediaRequestListWithViewContextResponse
public typealias MediaRequestListWithEmbedContextResponse = WordPressAPIInternal.MediaRequestListWithEmbedContextResponse

// MARK: - Comments
public typealias SparseComment = WordPressAPIInternal.SparseComment
public typealias CommentWithEditContext = WordPressAPIInternal.CommentWithEditContext
public typealias CommentWithViewContext = WordPressAPIInternal.CommentWithViewContext
public typealias CommentWithEmbedContext = WordPressAPIInternal.CommentWithEmbedContext
public typealias CommentListParams = WordPressAPIInternal.CommentListParams
public typealias CommentCreateParams = WordPressAPIInternal.CommentCreateParams
public typealias CommentUpdateParams = WordPressAPIInternal.CommentUpdateParams
public typealias CommentDeleteParams = WordPressAPIInternal.CommentDeleteParams
public typealias CommentStatus = WordPressAPIInternal.CommentStatus
public typealias CommentType = WordPressAPIInternal.CommentType
public typealias CommentsRequestExecutor = WordPressAPIInternal.CommentsRequestExecutor

public typealias CommentsRequestListWithEditContextResponse = WordPressAPIInternal.CommentsRequestListWithEditContextResponse
public typealias CommentsRequestListWithViewContextResponse = WordPressAPIInternal.CommentsRequestListWithViewContextResponse
public typealias CommentsRequestListWithEmbedContextResponse = WordPressAPIInternal.CommentsRequestListWithEmbedContextResponse

// MARK: - Tags
public typealias TagId = WordPressAPIInternal.TagId
public typealias SparseTag = WordPressAPIInternal.SparseTag
public typealias TagWithEditContext = WordPressAPIInternal.TagWithEditContext
public typealias TagWithViewContext = WordPressAPIInternal.TagWithViewContext
public typealias TagWithEmbedContext = WordPressAPIInternal.TagWithEmbedContext
public typealias TagCreateParams = WordPressAPIInternal.TagCreateParams
public typealias TagUpdateParams = WordPressAPIInternal.TagUpdateParams
public typealias TagListParams = WordPressAPIInternal.TagListParams
public typealias WpApiParamTagsOrderBy = WordPressAPIInternal.WpApiParamTagsOrderBy
public typealias TagsRequestExecutor = WordPressAPIInternal.TagsRequestExecutor
public typealias TagsRequestListWithEditContextResponse = WordPressAPIInternal.TagsRequestListWithEditContextResponse
public typealias TagsRequestListWithViewContextResponse = WordPressAPIInternal.TagsRequestListWithViewContextResponse
public typealias TagsRequestListWithEmbedContextResponse = WordPressAPIInternal.TagsRequestListWithEmbedContextResponse

// MARK: - Categories
public typealias CategoryId = WordPressAPIInternal.CategoryId
public typealias SparseCategory = WordPressAPIInternal.SparseCategory
public typealias CategoryWithEditContext = WordPressAPIInternal.CategoryWithEditContext
public typealias CategoryWithViewContext = WordPressAPIInternal.CategoryWithViewContext
public typealias CategoryWithEmbedContext = WordPressAPIInternal.CategoryWithEmbedContext
public typealias CategoryCreateParams = WordPressAPIInternal.CategoryCreateParams
public typealias CategoryUpdateParams = WordPressAPIInternal.CategoryUpdateParams
public typealias CategoryListParams = WordPressAPIInternal.CategoryListParams
public typealias WpApiParamCategoriesOrderBy = WordPressAPIInternal.WpApiParamCategoriesOrderBy
public typealias CategoriesRequestExecutor = WordPressAPIInternal.CategoriesRequestExecutor
public typealias CategoriesRequestListWithEditContextResponse = WordPressAPIInternal.CategoriesRequestListWithEditContextResponse
public typealias CategoriesRequestListWithViewContextResponse = WordPressAPIInternal.CategoriesRequestListWithViewContextResponse
public typealias CategoriesRequestListWithEmbedContextResponse = WordPressAPIInternal.CategoriesRequestListWithEmbedContextResponse

// MARK: – Site Settings
public typealias SparseSiteSettings = WordPressAPIInternal.SparseSiteSettings
public typealias SiteSettingsWithEditContext = WordPressAPIInternal.SiteSettingsWithEditContext
public typealias SiteSettingsWithViewContext = WordPressAPIInternal.SiteSettingsWithViewContext
public typealias SiteSettingsWithEmbedContext = WordPressAPIInternal.SiteSettingsWithEmbedContext

// MARK: – Site Settings
public typealias SiteSettingsRequestExecutor = WordPressAPIInternal.SiteSettingsRequestExecutor

// MARK: – Site Health Tests
public typealias WpSiteHealthTestsRequestExecutor = WordPressAPIInternal.WpSiteHealthTestsRequestExecutor
// swiftlint:enable line_length

// MARK: - Block Editor
public typealias WpBlockEditorSettingsParams = WordPressAPIInternal.WpBlockEditorSettingsParams

// MARK: - WordPress.org
public typealias WordPressOrgApiClient = WordPressAPIInternal.WordPressOrgApiClient

// MARK: - WordPress.com

// MARK: OAuth2
public typealias TokenValidationParameters = WordPressAPIInternal.TokenValidationParameters

// MARK: Subscribers
public typealias SubscribersListParams = WordPressAPIInternal.SubscribersListParams
public typealias SubscriberImportJobsListParams = WordPressAPIInternal.SubscriberImportJobsListParams
public typealias AddSubscribersParams = WordPressAPIInternal.AddSubscribersParams

// MARK: Support Bots
public typealias CreateBotConversationParams = WordPressAPIInternal.CreateBotConversationParams
public typealias AddMessageToBotConversationParams = WordPressAPIInternal.AddMessageToBotConversationParams
public typealias GetBotConversationParams = WordPressAPIInternal.GetBotConversationParams
public typealias CreateBotConversationFeedbackParams = WordPressAPIInternal.CreateBotConversationFeedbackParams

// MARK: Support Tickets
public typealias CreateSupportTicketParams = WordPressAPIInternal.CreateSupportTicketParams
public typealias AddMessageToSupportConversationParams = WordPressAPIInternal.AddMessageToSupportConversationParams

// MARK: - Jetpack
public typealias JetpackConnectionClient = WordPressAPIInternal.JetpackConnectionClient
