// Expose necessary Rust APIs as public API to the Swift package's consumers.
//
// We could export all of them using `@_exported import`, but that probably puts
// us in a position where we need to make major releases due to Rust code changes.
// swiftlint:disable line_length

import WordPressAPIInternal

public typealias WpApiError = WordPressAPIInternal.WpApiError
public typealias RequestExecutionError = WordPressAPIInternal.RequestExecutionError
public typealias ParsedUrl = WordPressAPIInternal.ParsedUrl
public typealias WpUuid = WordPressAPIInternal.WpUuid
public typealias WpNetworkRequest = WordPressAPIInternal.WpNetworkRequest
public typealias WpNetworkResponse = WordPressAPIInternal.WpNetworkResponse
public typealias WpNetworkHeaderMap = WordPressAPIInternal.WpNetworkHeaderMap
public typealias MiddlewarePipeline = WordPressAPIInternal.WpApiMiddlewarePipeline
public typealias MiddlewarePipelineBuilder = WordPressAPIInternal.WpApiMiddlewarePipelineBuilder
public typealias HttpAuthenticationMiddleware = WordPressAPIInternal.HttpAuthenticationMiddleware
public typealias RetryMiddleware = WordPressAPIInternal.RetryMiddleware

// MARK: - Login

public typealias WpApiApplicationPasswordDetails = WordPressAPIInternal.WpApiApplicationPasswordDetails
public typealias WpAuthentication = WordPressAPIInternal.WpAuthentication
public typealias SSLCertificateInfo = WordPressAPIInternal.SslCertificateInfo

// MARK: - Users

public typealias UserId = WordPressAPIInternal.UserId
public typealias SparseUser = WordPressAPIInternal.SparseUser
public typealias UserWithViewContext = WordPressAPIInternal.UserWithViewContext
public typealias UserWithEditContext = WordPressAPIInternal.UserWithEditContext
public typealias UserWithEmbedContext = WordPressAPIInternal.UserWithEmbedContext
public typealias UserListParams = WordPressAPIInternal.UserListParams
public typealias UserUpdateParams = WordPressAPIInternal.UserUpdateParams
public typealias UserCreateParams = WordPressAPIInternal.UserCreateParams
public typealias UserDeleteParams = WordPressAPIInternal.UserDeleteParams
public typealias UserDeleteResponse = WordPressAPIInternal.UserDeleteResponse
public typealias UsersRequestExecutor = WordPressAPIInternal.UsersRequestExecutor

public typealias UsersRequestListWithEditContextResponse = WordPressAPIInternal.UsersRequestListWithEditContextResponse
public typealias UsersRequestListWithViewContextResponse = WordPressAPIInternal.UsersRequestListWithViewContextResponse
public typealias UsersRequestListWithEmbedContextResponse = WordPressAPIInternal.UsersRequestListWithEmbedContextResponse

// MARK: - Plugins

public typealias SparsePlugin = WordPressAPIInternal.SparsePlugin
public typealias PluginWithViewContext = WordPressAPIInternal.PluginWithViewContext
public typealias PluginWithEditContext = WordPressAPIInternal.PluginWithEditContext
public typealias PluginWithEmbedContext = WordPressAPIInternal.PluginWithEmbedContext
public typealias PluginSlug = WordPressAPIInternal.PluginSlug
public typealias PluginWpOrgDirectorySlug = WordPressAPIInternal.PluginWpOrgDirectorySlug
public typealias PluginListParams = WordPressAPIInternal.PluginListParams
public typealias PluginUpdateParams = WordPressAPIInternal.PluginUpdateParams
public typealias PluginCreateParams = WordPressAPIInternal.PluginCreateParams
public typealias PluginDeleteResponse = WordPressAPIInternal.PluginDeleteResponse
public typealias PluginsRequestExecutor = WordPressAPIInternal.PluginsRequestExecutor

// MARK: – Application Passwords

public typealias SparseApplicationPassword = WordPressAPIInternal.SparseApplicationPassword
public typealias ApplicationPasswordWithEditContext = WordPressAPIInternal.ApplicationPasswordWithEditContext
public typealias ApplicationPasswordWithViewContext = WordPressAPIInternal.ApplicationPasswordWithViewContext
public typealias ApplicationPasswordWithEmbedContext = WordPressAPIInternal.ApplicationPasswordWithEmbedContext
public typealias ApplicationPasswordsRequestExecutor = WordPressAPIInternal.ApplicationPasswordsRequestExecutor

// MARK: - Site Health Checks
public typealias SiteHealthTest = WordPressAPIInternal.WpSiteHealthTest
public typealias SiteHealthDirectorySizes = WordPressAPIInternal.WpSiteHealthDirectorySizes

// MARK: – Post Types
public typealias PostType = WordPressAPIInternal.PostType
public typealias SparsePostType = WordPressAPIInternal.SparsePostTypeDetails
public typealias PostTypeWithEditContext = WordPressAPIInternal.PostTypeDetailsWithEditContext
public typealias PostTypeWithViewContext = WordPressAPIInternal.PostTypeDetailsWithViewContext
public typealias PostTypeWithEmbedContext = WordPressAPIInternal.PostTypeDetailsWithEmbedContext
public typealias PostTypeDetailsWithEditContext = WordPressAPIInternal.PostTypeDetailsWithEditContext
public typealias PostTypeDetailsWithViewContext = WordPressAPIInternal.PostTypeDetailsWithViewContext
public typealias PostTypeDetailsWithEmbedContext = WordPressAPIInternal.PostTypeDetailsWithEmbedContext
public typealias PostTypesRequestExecutor = WordPressAPIInternal.PostTypesRequestExecutor

// MARK: - Posts
public typealias SparsePost = WordPressAPIInternal.SparsePost
public typealias PostWithEditContext = WordPressAPIInternal.PostWithEditContext
public typealias PostWithViewContext = WordPressAPIInternal.PostWithViewContext
public typealias PostWithEmbedContext = WordPressAPIInternal.PostWithEmbedContext
public typealias PostListParams = WordPressAPIInternal.PostListParams
public typealias PostsRequestExecutor = WordPressAPIInternal.PostsRequestExecutor

public typealias PostsRequestListWithEditContextResponse = WordPressAPIInternal.PostsRequestListWithEditContextResponse
public typealias PostsRequestListWithViewContextResponse = WordPressAPIInternal.PostsRequestListWithViewContextResponse
public typealias PostsRequestListWithEmbedContextResponse = WordPressAPIInternal.PostsRequestListWithEmbedContextResponse

// MARK: - Media
public typealias SparseMedia = WordPressAPIInternal.SparseMedia
public typealias MediaUploadRequest = WordPressAPIInternal.MediaUploadRequest
public typealias MediaWithEditContext = WordPressAPIInternal.MediaWithEditContext
public typealias MediaWithViewContext = WordPressAPIInternal.MediaWithViewContext
public typealias MediaWithEmbedContext = WordPressAPIInternal.MediaWithEmbedContext
public typealias MediaListParams = WordPressAPIInternal.MediaListParams
public typealias MediaRequestExecutor = WordPressAPIInternal.MediaRequestExecutor

public typealias MediaRequestListWithEditContextResponse = WordPressAPIInternal.MediaRequestListWithEditContextResponse
public typealias MediaRequestListWithViewContextResponse = WordPressAPIInternal.MediaRequestListWithViewContextResponse
public typealias MediaRequestListWithEmbedContextResponse = WordPressAPIInternal.MediaRequestListWithEmbedContextResponse

// MARK: – Site Settings
public typealias SparseSiteSettings = WordPressAPIInternal.SparseSiteSettings
public typealias SiteSettingsWithEditContext = WordPressAPIInternal.SiteSettingsWithEditContext
public typealias SiteSettingsWithViewContext = WordPressAPIInternal.SiteSettingsWithViewContext
public typealias SiteSettingsWithEmbedContext = WordPressAPIInternal.SiteSettingsWithEmbedContext

// MARK: – Site Settings
public typealias SiteSettingsRequestExecutor = WordPressAPIInternal.SiteSettingsRequestExecutor

// MARK: – Site Health Tests
public typealias WpSiteHealthTestsRequestExecutor = WordPressAPIInternal.WpSiteHealthTestsRequestExecutor
// swiftlint:enable line_length

// MARK: - WordPress.org
public typealias WordPressOrgApiClient = WordPressAPIInternal.WordPressOrgApiClient
