[package]
name = "wp_networking"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wp_networking"

[dependencies]
uniffi = { workspace = true }
wp_api = { path = "../wp_api" }
reqwest = { version = "0.11.22", features = ["blocking"] }

[build-dependencies]
uniffi = { workspace = true , features = [ "build", "cli" ] }
