[bindings.swift]
ffi_module_name = "libwordpressFFI"
ffi_module_filename = "wp_localization_uniffi"
generate_module_map = false
generate_immutable_records = false
experimental_sendable_value_types = true
