[package]
name = "wordpress-rs"
version = "0.1.0"
edition = "2024"
description = "A command-line interface for interacting with WordPress sites"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
wp_api = { path = "../wp_api", features = [ "reqwest-request-executor" ] }

[[bin]]
name = "wp_rs_cli"
